// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for DependencyCheckStatus.
const (
	DependencyCheckStatusError   DependencyCheckStatus = "error"
	DependencyCheckStatusOk      DependencyCheckStatus = "ok"
	DependencyCheckStatusSkipped DependencyCheckStatus = "skipped"
)

// Valid indicates whether the value is a known member of the DependencyCheckStatus enum.
func (e DependencyCheckStatus) Valid() bool {
	switch e {
	case DependencyCheckStatusError:
		return true
	case DependencyCheckStatusOk:
		return true
	case DependencyCheckStatusSkipped:
		return true
	default:
		return false
	}
}

// Defines values for EchoResponseScheme.
const (
	EchoResponseSchemeHttp  EchoResponseScheme = "http"
	EchoResponseSchemeHttps EchoResponseScheme = "https"
)

// Valid indicates whether the value is a known member of the EchoResponseScheme enum.
func (e EchoResponseScheme) Valid() bool {
	switch e {
	case EchoResponseSchemeHttp:
		return true
	case EchoResponseSchemeHttps:
		return true
	default:
		return false
	}
}

// Defines values for LivezResponseStatus.
const (
	LivezResponseStatusOk LivezResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the LivezResponseStatus enum.
func (e LivezResponseStatus) Valid() bool {
	switch e {
	case LivezResponseStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for ReadyzResponseStatus.
const (
	NotReady ReadyzResponseStatus = "not_ready"
	Ready    ReadyzResponseStatus = "ready"
)

// Valid indicates whether the value is a known member of the ReadyzResponseStatus enum.
func (e ReadyzResponseStatus) Valid() bool {
	switch e {
	case NotReady:
		return true
	case Ready:
		return true
	default:
		return false
	}
}

// Defines values for SchemeResponseScheme.
const (
	SchemeResponseSchemeHttp  SchemeResponseScheme = "http"
	SchemeResponseSchemeHttps SchemeResponseScheme = "https"
)

// Valid indicates whether the value is a known member of the SchemeResponseScheme enum.
func (e SchemeResponseScheme) Valid() bool {
	switch e {
	case SchemeResponseSchemeHttp:
		return true
	case SchemeResponseSchemeHttps:
		return true
	default:
		return false
	}
}

// Defines values for StartupzResponseStatus.
const (
	Started  StartupzResponseStatus = "started"
	Starting StartupzResponseStatus = "starting"
)

// Valid indicates whether the value is a known member of the StartupzResponseStatus enum.
func (e StartupzResponseStatus) Valid() bool {
	switch e {
	case Started:
		return true
	case Starting:
		return true
	default:
		return false
	}
}

// Defines values for UserResponseRole.
const (
	Admin UserResponseRole = "admin"
	User  UserResponseRole = "user"
)

// Valid indicates whether the value is a known member of the UserResponseRole enum.
func (e UserResponseRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case User:
		return true
	default:
		return false
	}
}

// DelayResponse defines model for DelayResponse.
type DelayResponse struct {
	// Delay The number of seconds the response was delayed.
	Delay float64 `json:"delay"`
}

// DependencyCheck defines model for DependencyCheck.
type DependencyCheck struct {
	Message *string               `json:"message,omitempty"`
	Status  DependencyCheckStatus `json:"status"`
}

// DependencyCheckStatus defines model for DependencyCheck.Status.
type DependencyCheckStatus string

// EchoResponse defines model for EchoResponse.
type EchoResponse struct {
	// Body The request body echoed back verbatim. Null for methods that carry no body (such as GET).
	Body *string `json:"body,omitempty"`

	// Headers A mapping of names to their list of values, used for both HTTP headers and query parameters (each may appear more than once).
	Headers HeaderMap `json:"headers"`
	Method  string    `json:"method"`

	// Origin The caller's origin IP address.
	Origin string `json:"origin"`
	Path   string `json:"path"`

	// Query A mapping of names to their list of values, used for both HTTP headers and query parameters (each may appear more than once).
	Query HeaderMap `json:"query"`

	// Scheme The scheme (http or https) of the incoming request.
	Scheme EchoResponseScheme `json:"scheme"`
}

// EchoResponseScheme The scheme (http or https) of the incoming request.
type EchoResponseScheme string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error A human-readable description of the error.
	Error string `json:"error"`
}

// HeaderMap A mapping of names to their list of values, used for both HTTP headers and query parameters (each may appear more than once).
type HeaderMap map[string][]string

// HeadersResponse defines model for HeadersResponse.
type HeadersResponse struct {
	// Headers A mapping of names to their list of values, used for both HTTP headers and query parameters (each may appear more than once).
	Headers HeaderMap `json:"headers"`
}

// IpResponse defines model for IpResponse.
type IpResponse struct {
	// Origin The caller's origin IP address.
	Origin string `json:"origin"`
}

// LivezResponse defines model for LivezResponse.
type LivezResponse struct {
	Status LivezResponseStatus `json:"status"`
}

// LivezResponseStatus defines model for LivezResponse.Status.
type LivezResponseStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Password The account password.
	Password string `json:"password"`

	// Username The account username.
	Username string `json:"username"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	// Message A human-readable acknowledgement.
	Message string `json:"message"`
}

// PasswordChangeRequest defines model for PasswordChangeRequest.
type PasswordChangeRequest struct {
	// CurrentPassword The account's current password, re-verified before the change.
	CurrentPassword string `json:"currentPassword"`

	// NewPassword The new password (stored only as a bcrypt hash).
	NewPassword string `json:"newPassword"`
}

// PasswordResetRequest defines model for PasswordResetRequest.
type PasswordResetRequest struct {
	// NewPassword The new password (stored only as a bcrypt hash).
	NewPassword string `json:"newPassword"`

	// Token The single-use reset token issued by /auth/password/reset-request.
	Token string `json:"token"`
}

// PasswordResetRequestRequest defines model for PasswordResetRequestRequest.
type PasswordResetRequestRequest struct {
	// Username The username to issue a reset token for.
	Username string `json:"username"`
}

// PasswordResetResponse defines model for PasswordResetResponse.
type PasswordResetResponse struct {
	// Message A human-readable acknowledgement.
	Message string `json:"message"`

	// Token The single-use reset token, present only when the user exists. In production this would be emailed instead of returned.
	Token *string `json:"token,omitempty"`
}

// ReadyzResponse defines model for ReadyzResponse.
type ReadyzResponse struct {
	Checks map[string]DependencyCheck `json:"checks"`
	Status ReadyzResponseStatus       `json:"status"`
}

// ReadyzResponseStatus defines model for ReadyzResponse.Status.
type ReadyzResponseStatus string

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// Password The account password (stored only as a bcrypt hash).
	Password string `json:"password"`

	// Username The unique username for the new account.
	Username string `json:"username"`
}

// SchemeResponse defines model for SchemeResponse.
type SchemeResponse struct {
	// Scheme The scheme (http or https) of the incoming request.
	Scheme SchemeResponseScheme `json:"scheme"`
}

// SchemeResponseScheme The scheme (http or https) of the incoming request.
type SchemeResponseScheme string

// StartupzResponse defines model for StartupzResponse.
type StartupzResponse struct {
	Checks map[string]DependencyCheck `json:"checks"`
	Status StartupzResponseStatus     `json:"status"`
}

// StartupzResponseStatus defines model for StartupzResponse.Status.
type StartupzResponseStatus string

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	// Code The HTTP status code returned.
	Code int32 `json:"code"`

	// Description The canonical reason phrase for the status code, if known.
	Description *string `json:"description,omitempty"`
}

// UserAgentResponse defines model for UserAgentResponse.
type UserAgentResponse struct {
	UserAgent string `json:"user-agent"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	// Id The user's unique identifier.
	Id openapi_types.UUID `json:"id"`

	// Role The user's role.
	Role UserResponseRole `json:"role"`

	// Username The user's username.
	Username string `json:"username"`
}

// UserResponseRole The user's role.
type UserResponseRole string

// UuidResponse defines model for UuidResponse.
type UuidResponse struct {
	// Uuid A randomly generated version 4 UUID.
	Uuid openapi_types.UUID `json:"uuid"`
}

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	BuildTime time.Time `json:"build_time"`
	GitSha    string    `json:"git_sha"`
	GoVersion string    `json:"go_version"`
	Service   string    `json:"service"`
	Version   string    `json:"version"`
}

// CsrfTokenHeader defines model for CsrfTokenHeader.
type CsrfTokenHeader = string

// EchoBodyTooLarge defines model for EchoBodyTooLarge.
type EchoBodyTooLarge = ErrorResponse

// EchoReflection defines model for EchoReflection.
type EchoReflection = EchoResponse

// PostAuthLogoutParams defines parameters for PostAuthLogout.
type PostAuthLogoutParams struct {
	// XCSRFToken The CSRF token from the devopsbin_csrf cookie. Required in practice on state-changing requests to authenticated routes; a missing or mismatched token yields a 403 response. Must match the token bound to the current session.
	XCSRFToken *CsrfTokenHeader `json:"X-CSRF-Token,omitempty"`
}

// PostAuthPasswordChangeParams defines parameters for PostAuthPasswordChange.
type PostAuthPasswordChangeParams struct {
	// XCSRFToken The CSRF token from the devopsbin_csrf cookie. Required in practice on state-changing requests to authenticated routes; a missing or mismatched token yields a 403 response. Must match the token bound to the current session.
	XCSRFToken *CsrfTokenHeader `json:"X-CSRF-Token,omitempty"`
}

// DeleteEchoTextBody defines parameters for DeleteEcho.
type DeleteEchoTextBody = string

// PatchEchoTextBody defines parameters for PatchEcho.
type PatchEchoTextBody = string

// PostEchoTextBody defines parameters for PostEcho.
type PostEchoTextBody = string

// PutEchoTextBody defines parameters for PutEcho.
type PutEchoTextBody = string

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// PostAuthPasswordChangeJSONRequestBody defines body for PostAuthPasswordChange for application/json ContentType.
type PostAuthPasswordChangeJSONRequestBody = PasswordChangeRequest

// PostAuthPasswordResetJSONRequestBody defines body for PostAuthPasswordReset for application/json ContentType.
type PostAuthPasswordResetJSONRequestBody = PasswordResetRequest

// PostAuthPasswordResetRequestJSONRequestBody defines body for PostAuthPasswordResetRequest for application/json ContentType.
type PostAuthPasswordResetRequestJSONRequestBody = PasswordResetRequestRequest

// PostAuthRegisterJSONRequestBody defines body for PostAuthRegister for application/json ContentType.
type PostAuthRegisterJSONRequestBody = RegisterRequest

// DeleteEchoTextRequestBody defines body for DeleteEcho for text/plain ContentType.
type DeleteEchoTextRequestBody = DeleteEchoTextBody

// PatchEchoTextRequestBody defines body for PatchEcho for text/plain ContentType.
type PatchEchoTextRequestBody = PatchEchoTextBody

// PostEchoTextRequestBody defines body for PostEcho for text/plain ContentType.
type PostEchoTextRequestBody = PostEchoTextBody

// PutEchoTextRequestBody defines body for PutEcho for text/plain ContentType.
type PutEchoTextRequestBody = PutEchoTextBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Log in with username and password
	// (POST /auth/login)
	PostAuthLogin(w http.ResponseWriter, r *http.Request)
	// Log out of the current session
	// (POST /auth/logout)
	PostAuthLogout(w http.ResponseWriter, r *http.Request, params PostAuthLogoutParams)
	// Return the current authenticated user
	// (GET /auth/me)
	GetAuthMe(w http.ResponseWriter, r *http.Request)
	// Change the current user's password
	// (POST /auth/password/change)
	PostAuthPasswordChange(w http.ResponseWriter, r *http.Request, params PostAuthPasswordChangeParams)
	// Reset a password using a reset token
	// (POST /auth/password/reset)
	PostAuthPasswordReset(w http.ResponseWriter, r *http.Request)
	// Request a password-reset token
	// (POST /auth/password/reset-request)
	PostAuthPasswordResetRequest(w http.ResponseWriter, r *http.Request)
	// Register a new user
	// (POST /auth/register)
	PostAuthRegister(w http.ResponseWriter, r *http.Request)
	// Delay the response by a given number of seconds
	// (GET /delay/{seconds})
	GetDelay(w http.ResponseWriter, r *http.Request, seconds float64)
	// Echo the incoming request
	// (DELETE /echo)
	DeleteEcho(w http.ResponseWriter, r *http.Request)
	// Echo the incoming request
	// (GET /echo)
	GetEcho(w http.ResponseWriter, r *http.Request)
	// Echo the incoming request
	// (PATCH /echo)
	PatchEcho(w http.ResponseWriter, r *http.Request)
	// Echo the incoming request
	// (POST /echo)
	PostEcho(w http.ResponseWriter, r *http.Request)
	// Echo the incoming request
	// (PUT /echo)
	PutEcho(w http.ResponseWriter, r *http.Request)
	// Echo the request headers
	// (GET /headers)
	GetHeaders(w http.ResponseWriter, r *http.Request)
	// Return the caller's IP address
	// (GET /ip)
	GetIp(w http.ResponseWriter, r *http.Request)
	// Liveness probe
	// (GET /livez)
	GetLivez(w http.ResponseWriter, r *http.Request)
	// Readiness probe
	// (GET /readyz)
	GetReadyz(w http.ResponseWriter, r *http.Request)
	// Return the request scheme
	// (GET /scheme)
	GetScheme(w http.ResponseWriter, r *http.Request)
	// Startup probe
	// (GET /startupz)
	GetStartupz(w http.ResponseWriter, r *http.Request)
	// Return a given HTTP status code
	// (GET /status/{code})
	GetStatus(w http.ResponseWriter, r *http.Request, code int32)
	// Echo the User-Agent header
	// (GET /user-agent)
	GetUserAgent(w http.ResponseWriter, r *http.Request)
	// Generate a random UUID
	// (GET /uuid)
	GetUuid(w http.ResponseWriter, r *http.Request)
	// Build and version metadata
	// (GET /version)
	GetVersion(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Log in with username and password
// (POST /auth/login)
func (_ Unimplemented) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Log out of the current session
// (POST /auth/logout)
func (_ Unimplemented) PostAuthLogout(w http.ResponseWriter, r *http.Request, params PostAuthLogoutParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Return the current authenticated user
// (GET /auth/me)
func (_ Unimplemented) GetAuthMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Change the current user's password
// (POST /auth/password/change)
func (_ Unimplemented) PostAuthPasswordChange(w http.ResponseWriter, r *http.Request, params PostAuthPasswordChangeParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reset a password using a reset token
// (POST /auth/password/reset)
func (_ Unimplemented) PostAuthPasswordReset(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Request a password-reset token
// (POST /auth/password/reset-request)
func (_ Unimplemented) PostAuthPasswordResetRequest(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register a new user
// (POST /auth/register)
func (_ Unimplemented) PostAuthRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delay the response by a given number of seconds
// (GET /delay/{seconds})
func (_ Unimplemented) GetDelay(w http.ResponseWriter, r *http.Request, seconds float64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Echo the incoming request
// (DELETE /echo)
func (_ Unimplemented) DeleteEcho(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Echo the incoming request
// (GET /echo)
func (_ Unimplemented) GetEcho(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Echo the incoming request
// (PATCH /echo)
func (_ Unimplemented) PatchEcho(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Echo the incoming request
// (POST /echo)
func (_ Unimplemented) PostEcho(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Echo the incoming request
// (PUT /echo)
func (_ Unimplemented) PutEcho(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Echo the request headers
// (GET /headers)
func (_ Unimplemented) GetHeaders(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Return the caller's IP address
// (GET /ip)
func (_ Unimplemented) GetIp(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness probe
// (GET /livez)
func (_ Unimplemented) GetLivez(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Readiness probe
// (GET /readyz)
func (_ Unimplemented) GetReadyz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Return the request scheme
// (GET /scheme)
func (_ Unimplemented) GetScheme(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Startup probe
// (GET /startupz)
func (_ Unimplemented) GetStartupz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Return a given HTTP status code
// (GET /status/{code})
func (_ Unimplemented) GetStatus(w http.ResponseWriter, r *http.Request, code int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Echo the User-Agent header
// (GET /user-agent)
func (_ Unimplemented) GetUserAgent(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Generate a random UUID
// (GET /uuid)
func (_ Unimplemented) GetUuid(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Build and version metadata
// (GET /version)
func (_ Unimplemented) GetVersion(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogout(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PostAuthLogoutParams

	headers := r.Header

	// ------------- Optional header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CsrfTokenHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-CSRF-Token", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-CSRF-Token", Err: err})
			return
		}

		params.XCSRFToken = &XCSRFToken

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogout(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthMe operation middleware
func (siw *ServerInterfaceWrapper) GetAuthMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthPasswordChange operation middleware
func (siw *ServerInterfaceWrapper) PostAuthPasswordChange(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PostAuthPasswordChangeParams

	headers := r.Header

	// ------------- Optional header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CsrfTokenHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-CSRF-Token", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-CSRF-Token", Err: err})
			return
		}

		params.XCSRFToken = &XCSRFToken

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthPasswordChange(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthPasswordReset operation middleware
func (siw *ServerInterfaceWrapper) PostAuthPasswordReset(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthPasswordReset(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthPasswordResetRequest operation middleware
func (siw *ServerInterfaceWrapper) PostAuthPasswordResetRequest(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthPasswordResetRequest(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthRegister operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDelay operation middleware
func (siw *ServerInterfaceWrapper) GetDelay(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "seconds" -------------
	var seconds float64

	err = runtime.BindStyledParameterWithOptions("simple", "seconds", chi.URLParam(r, "seconds"), &seconds, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "number", Format: "double"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "seconds", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDelay(w, r, seconds)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteEcho operation middleware
func (siw *ServerInterfaceWrapper) DeleteEcho(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteEcho(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEcho operation middleware
func (siw *ServerInterfaceWrapper) GetEcho(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEcho(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchEcho operation middleware
func (siw *ServerInterfaceWrapper) PatchEcho(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchEcho(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEcho operation middleware
func (siw *ServerInterfaceWrapper) PostEcho(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEcho(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutEcho operation middleware
func (siw *ServerInterfaceWrapper) PutEcho(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutEcho(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHeaders operation middleware
func (siw *ServerInterfaceWrapper) GetHeaders(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHeaders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetIp operation middleware
func (siw *ServerInterfaceWrapper) GetIp(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLivez operation middleware
func (siw *ServerInterfaceWrapper) GetLivez(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLivez(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetScheme operation middleware
func (siw *ServerInterfaceWrapper) GetScheme(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetScheme(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStartupz operation middleware
func (siw *ServerInterfaceWrapper) GetStartupz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStartupz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetStatus(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "code" -------------
	var code int32

	err = runtime.BindStyledParameterWithOptions("simple", "code", chi.URLParam(r, "code"), &code, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatus(w, r, code)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserAgent operation middleware
func (siw *ServerInterfaceWrapper) GetUserAgent(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserAgent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUuid operation middleware
func (siw *ServerInterfaceWrapper) GetUuid(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUuid(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.PostAuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.PostAuthLogout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/me", wrapper.GetAuthMe)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/password/change", wrapper.PostAuthPasswordChange)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/password/reset", wrapper.PostAuthPasswordReset)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/password/reset-request", wrapper.PostAuthPasswordResetRequest)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.PostAuthRegister)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/delay/{seconds}", wrapper.GetDelay)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/echo", wrapper.DeleteEcho)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/echo", wrapper.GetEcho)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/echo", wrapper.PatchEcho)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/echo", wrapper.PostEcho)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/echo", wrapper.PutEcho)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/headers", wrapper.GetHeaders)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ip", wrapper.GetIp)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/livez", wrapper.GetLivez)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.GetReadyz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/scheme", wrapper.GetScheme)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/startupz", wrapper.GetStartupz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/status/{code}", wrapper.GetStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/user-agent", wrapper.GetUserAgent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/uuid", wrapper.GetUuid)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/version", wrapper.GetVersion)
	})

	return r
}

type EchoBodyTooLargeJSONResponse ErrorResponse

type EchoReflectionJSONResponse EchoResponse

type PostAuthLoginRequestObject struct {
	Body *PostAuthLoginJSONRequestBody
}

type PostAuthLoginResponseObject interface {
	VisitPostAuthLoginResponse(w http.ResponseWriter) error
}

type PostAuthLogin200ResponseHeaders struct {
	SetCookie *string
}

type PostAuthLogin200JSONResponse struct {
	Body    UserResponse
	Headers PostAuthLogin200ResponseHeaders
}

func (response PostAuthLogin200JSONResponse) VisitPostAuthLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthLogin400JSONResponse ErrorResponse

func (response PostAuthLogin400JSONResponse) VisitPostAuthLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthLogin401JSONResponse ErrorResponse

func (response PostAuthLogin401JSONResponse) VisitPostAuthLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthLogin423ResponseHeaders struct {
	RetryAfter *int32
}

type PostAuthLogin423JSONResponse struct {
	Body    ErrorResponse
	Headers PostAuthLogin423ResponseHeaders
}

func (response PostAuthLogin423JSONResponse) VisitPostAuthLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(423)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthLogoutRequestObject struct {
	Params PostAuthLogoutParams
}

type PostAuthLogoutResponseObject interface {
	VisitPostAuthLogoutResponse(w http.ResponseWriter) error
}

type PostAuthLogout204ResponseHeaders struct {
	SetCookie *string
}

type PostAuthLogout204Response struct {
	Headers PostAuthLogout204ResponseHeaders
}

func (response PostAuthLogout204Response) VisitPostAuthLogoutResponse(w http.ResponseWriter) error {
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(204)
	return nil
}

type PostAuthLogout401JSONResponse ErrorResponse

func (response PostAuthLogout401JSONResponse) VisitPostAuthLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthLogout403JSONResponse ErrorResponse

func (response PostAuthLogout403JSONResponse) VisitPostAuthLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthMeRequestObject struct {
}

type GetAuthMeResponseObject interface {
	VisitGetAuthMeResponse(w http.ResponseWriter) error
}

type GetAuthMe200JSONResponse UserResponse

func (response GetAuthMe200JSONResponse) VisitGetAuthMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthMe401JSONResponse ErrorResponse

func (response GetAuthMe401JSONResponse) VisitGetAuthMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthPasswordChangeRequestObject struct {
	Params PostAuthPasswordChangeParams
	Body   *PostAuthPasswordChangeJSONRequestBody
}

type PostAuthPasswordChangeResponseObject interface {
	VisitPostAuthPasswordChangeResponse(w http.ResponseWriter) error
}

type PostAuthPasswordChange200ResponseHeaders struct {
	SetCookie *string
}

type PostAuthPasswordChange200JSONResponse struct {
	Body    UserResponse
	Headers PostAuthPasswordChange200ResponseHeaders
}

func (response PostAuthPasswordChange200JSONResponse) VisitPostAuthPasswordChangeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthPasswordChange400JSONResponse ErrorResponse

func (response PostAuthPasswordChange400JSONResponse) VisitPostAuthPasswordChangeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthPasswordChange401JSONResponse ErrorResponse

func (response PostAuthPasswordChange401JSONResponse) VisitPostAuthPasswordChangeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthPasswordChange403JSONResponse ErrorResponse

func (response PostAuthPasswordChange403JSONResponse) VisitPostAuthPasswordChangeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthPasswordResetRequestObject struct {
	Body *PostAuthPasswordResetJSONRequestBody
}

type PostAuthPasswordResetResponseObject interface {
	VisitPostAuthPasswordResetResponse(w http.ResponseWriter) error
}

type PostAuthPasswordReset200JSONResponse MessageResponse

func (response PostAuthPasswordReset200JSONResponse) VisitPostAuthPasswordResetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthPasswordReset400JSONResponse ErrorResponse

func (response PostAuthPasswordReset400JSONResponse) VisitPostAuthPasswordResetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthPasswordReset410JSONResponse ErrorResponse

func (response PostAuthPasswordReset410JSONResponse) VisitPostAuthPasswordResetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(410)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthPasswordResetRequestRequestObject struct {
	Body *PostAuthPasswordResetRequestJSONRequestBody
}

type PostAuthPasswordResetRequestResponseObject interface {
	VisitPostAuthPasswordResetRequestResponse(w http.ResponseWriter) error
}

type PostAuthPasswordResetRequest200JSONResponse PasswordResetResponse

func (response PostAuthPasswordResetRequest200JSONResponse) VisitPostAuthPasswordResetRequestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthPasswordResetRequest400JSONResponse ErrorResponse

func (response PostAuthPasswordResetRequest400JSONResponse) VisitPostAuthPasswordResetRequestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthRegisterRequestObject struct {
	Body *PostAuthRegisterJSONRequestBody
}

type PostAuthRegisterResponseObject interface {
	VisitPostAuthRegisterResponse(w http.ResponseWriter) error
}

type PostAuthRegister201ResponseHeaders struct {
	SetCookie *string
}

type PostAuthRegister201JSONResponse struct {
	Body    UserResponse
	Headers PostAuthRegister201ResponseHeaders
}

func (response PostAuthRegister201JSONResponse) VisitPostAuthRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthRegister400JSONResponse ErrorResponse

func (response PostAuthRegister400JSONResponse) VisitPostAuthRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthRegister409JSONResponse ErrorResponse

func (response PostAuthRegister409JSONResponse) VisitPostAuthRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetDelayRequestObject struct {
	Seconds float64 `json:"seconds"`
}

type GetDelayResponseObject interface {
	VisitGetDelayResponse(w http.ResponseWriter) error
}

type GetDelay200JSONResponse DelayResponse

func (response GetDelay200JSONResponse) VisitGetDelayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetDelay400JSONResponse ErrorResponse

func (response GetDelay400JSONResponse) VisitGetDelayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteEchoRequestObject struct {
	Body *DeleteEchoTextRequestBody
}

type DeleteEchoResponseObject interface {
	VisitDeleteEchoResponse(w http.ResponseWriter) error
}

type DeleteEcho200JSONResponse struct{ EchoReflectionJSONResponse }

func (response DeleteEcho200JSONResponse) VisitDeleteEchoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteEcho413JSONResponse struct{ EchoBodyTooLargeJSONResponse }

func (response DeleteEcho413JSONResponse) VisitDeleteEchoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type GetEchoRequestObject struct {
}

type GetEchoResponseObject interface {
	VisitGetEchoResponse(w http.ResponseWriter) error
}

type GetEcho200JSONResponse EchoResponse

func (response GetEcho200JSONResponse) VisitGetEchoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PatchEchoRequestObject struct {
	Body *PatchEchoTextRequestBody
}

type PatchEchoResponseObject interface {
	VisitPatchEchoResponse(w http.ResponseWriter) error
}

type PatchEcho200JSONResponse struct{ EchoReflectionJSONResponse }

func (response PatchEcho200JSONResponse) VisitPatchEchoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PatchEcho413JSONResponse struct{ EchoBodyTooLargeJSONResponse }

func (response PatchEcho413JSONResponse) VisitPatchEchoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type PostEchoRequestObject struct {
	Body *PostEchoTextRequestBody
}

type PostEchoResponseObject interface {
	VisitPostEchoResponse(w http.ResponseWriter) error
}

type PostEcho200JSONResponse struct{ EchoReflectionJSONResponse }

func (response PostEcho200JSONResponse) VisitPostEchoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostEcho413JSONResponse struct{ EchoBodyTooLargeJSONResponse }

func (response PostEcho413JSONResponse) VisitPostEchoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type PutEchoRequestObject struct {
	Body *PutEchoTextRequestBody
}

type PutEchoResponseObject interface {
	VisitPutEchoResponse(w http.ResponseWriter) error
}

type PutEcho200JSONResponse struct{ EchoReflectionJSONResponse }

func (response PutEcho200JSONResponse) VisitPutEchoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PutEcho413JSONResponse struct{ EchoBodyTooLargeJSONResponse }

func (response PutEcho413JSONResponse) VisitPutEchoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type GetHeadersRequestObject struct {
}

type GetHeadersResponseObject interface {
	VisitGetHeadersResponse(w http.ResponseWriter) error
}

type GetHeaders200JSONResponse HeadersResponse

func (response GetHeaders200JSONResponse) VisitGetHeadersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetIpRequestObject struct {
}

type GetIpResponseObject interface {
	VisitGetIpResponse(w http.ResponseWriter) error
}

type GetIp200JSONResponse IpResponse

func (response GetIp200JSONResponse) VisitGetIpResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetLivezRequestObject struct {
}

type GetLivezResponseObject interface {
	VisitGetLivezResponse(w http.ResponseWriter) error
}

type GetLivez200JSONResponse LivezResponse

func (response GetLivez200JSONResponse) VisitGetLivezResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyzRequestObject struct {
}

type GetReadyzResponseObject interface {
	VisitGetReadyzResponse(w http.ResponseWriter) error
}

type GetReadyz200JSONResponse ReadyzResponse

func (response GetReadyz200JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyz503JSONResponse ReadyzResponse

func (response GetReadyz503JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetSchemeRequestObject struct {
}

type GetSchemeResponseObject interface {
	VisitGetSchemeResponse(w http.ResponseWriter) error
}

type GetScheme200JSONResponse SchemeResponse

func (response GetScheme200JSONResponse) VisitGetSchemeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetStartupzRequestObject struct {
}

type GetStartupzResponseObject interface {
	VisitGetStartupzResponse(w http.ResponseWriter) error
}

type GetStartupz200JSONResponse StartupzResponse

func (response GetStartupz200JSONResponse) VisitGetStartupzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetStartupz503JSONResponse StartupzResponse

func (response GetStartupz503JSONResponse) VisitGetStartupzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetStatusRequestObject struct {
	Code int32 `json:"code"`
}

type GetStatusResponseObject interface {
	VisitGetStatusResponse(w http.ResponseWriter) error
}

type GetStatus400JSONResponse ErrorResponse

func (response GetStatus400JSONResponse) VisitGetStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetStatusdefaultJSONResponse struct {
	Body       StatusResponse
	StatusCode int
}

func (response GetStatusdefaultJSONResponse) VisitGetStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetUserAgentRequestObject struct {
}

type GetUserAgentResponseObject interface {
	VisitGetUserAgentResponse(w http.ResponseWriter) error
}

type GetUserAgent200JSONResponse UserAgentResponse

func (response GetUserAgent200JSONResponse) VisitGetUserAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetUuidRequestObject struct {
}

type GetUuidResponseObject interface {
	VisitGetUuidResponse(w http.ResponseWriter) error
}

type GetUuid200JSONResponse UuidResponse

func (response GetUuid200JSONResponse) VisitGetUuidResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetVersionRequestObject struct {
}

type GetVersionResponseObject interface {
	VisitGetVersionResponse(w http.ResponseWriter) error
}

type GetVersion200JSONResponse VersionResponse

func (response GetVersion200JSONResponse) VisitGetVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Log in with username and password
	// (POST /auth/login)
	PostAuthLogin(ctx context.Context, request PostAuthLoginRequestObject) (PostAuthLoginResponseObject, error)
	// Log out of the current session
	// (POST /auth/logout)
	PostAuthLogout(ctx context.Context, request PostAuthLogoutRequestObject) (PostAuthLogoutResponseObject, error)
	// Return the current authenticated user
	// (GET /auth/me)
	GetAuthMe(ctx context.Context, request GetAuthMeRequestObject) (GetAuthMeResponseObject, error)
	// Change the current user's password
	// (POST /auth/password/change)
	PostAuthPasswordChange(ctx context.Context, request PostAuthPasswordChangeRequestObject) (PostAuthPasswordChangeResponseObject, error)
	// Reset a password using a reset token
	// (POST /auth/password/reset)
	PostAuthPasswordReset(ctx context.Context, request PostAuthPasswordResetRequestObject) (PostAuthPasswordResetResponseObject, error)
	// Request a password-reset token
	// (POST /auth/password/reset-request)
	PostAuthPasswordResetRequest(ctx context.Context, request PostAuthPasswordResetRequestRequestObject) (PostAuthPasswordResetRequestResponseObject, error)
	// Register a new user
	// (POST /auth/register)
	PostAuthRegister(ctx context.Context, request PostAuthRegisterRequestObject) (PostAuthRegisterResponseObject, error)
	// Delay the response by a given number of seconds
	// (GET /delay/{seconds})
	GetDelay(ctx context.Context, request GetDelayRequestObject) (GetDelayResponseObject, error)
	// Echo the incoming request
	// (DELETE /echo)
	DeleteEcho(ctx context.Context, request DeleteEchoRequestObject) (DeleteEchoResponseObject, error)
	// Echo the incoming request
	// (GET /echo)
	GetEcho(ctx context.Context, request GetEchoRequestObject) (GetEchoResponseObject, error)
	// Echo the incoming request
	// (PATCH /echo)
	PatchEcho(ctx context.Context, request PatchEchoRequestObject) (PatchEchoResponseObject, error)
	// Echo the incoming request
	// (POST /echo)
	PostEcho(ctx context.Context, request PostEchoRequestObject) (PostEchoResponseObject, error)
	// Echo the incoming request
	// (PUT /echo)
	PutEcho(ctx context.Context, request PutEchoRequestObject) (PutEchoResponseObject, error)
	// Echo the request headers
	// (GET /headers)
	GetHeaders(ctx context.Context, request GetHeadersRequestObject) (GetHeadersResponseObject, error)
	// Return the caller's IP address
	// (GET /ip)
	GetIp(ctx context.Context, request GetIpRequestObject) (GetIpResponseObject, error)
	// Liveness probe
	// (GET /livez)
	GetLivez(ctx context.Context, request GetLivezRequestObject) (GetLivezResponseObject, error)
	// Readiness probe
	// (GET /readyz)
	GetReadyz(ctx context.Context, request GetReadyzRequestObject) (GetReadyzResponseObject, error)
	// Return the request scheme
	// (GET /scheme)
	GetScheme(ctx context.Context, request GetSchemeRequestObject) (GetSchemeResponseObject, error)
	// Startup probe
	// (GET /startupz)
	GetStartupz(ctx context.Context, request GetStartupzRequestObject) (GetStartupzResponseObject, error)
	// Return a given HTTP status code
	// (GET /status/{code})
	GetStatus(ctx context.Context, request GetStatusRequestObject) (GetStatusResponseObject, error)
	// Echo the User-Agent header
	// (GET /user-agent)
	GetUserAgent(ctx context.Context, request GetUserAgentRequestObject) (GetUserAgentResponseObject, error)
	// Generate a random UUID
	// (GET /uuid)
	GetUuid(ctx context.Context, request GetUuidRequestObject) (GetUuidResponseObject, error)
	// Build and version metadata
	// (GET /version)
	GetVersion(ctx context.Context, request GetVersionRequestObject) (GetVersionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PostAuthLogin operation middleware
func (sh *strictHandler) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	var request PostAuthLoginRequestObject

	var body PostAuthLoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthLogin(ctx, request.(PostAuthLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAuthLoginResponseObject); ok {
		if err := validResponse.VisitPostAuthLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuthLogout operation middleware
func (sh *strictHandler) PostAuthLogout(w http.ResponseWriter, r *http.Request, params PostAuthLogoutParams) {
	var request PostAuthLogoutRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthLogout(ctx, request.(PostAuthLogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthLogout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAuthLogoutResponseObject); ok {
		if err := validResponse.VisitPostAuthLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAuthMe operation middleware
func (sh *strictHandler) GetAuthMe(w http.ResponseWriter, r *http.Request) {
	var request GetAuthMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthMe(ctx, request.(GetAuthMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAuthMeResponseObject); ok {
		if err := validResponse.VisitGetAuthMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuthPasswordChange operation middleware
func (sh *strictHandler) PostAuthPasswordChange(w http.ResponseWriter, r *http.Request, params PostAuthPasswordChangeParams) {
	var request PostAuthPasswordChangeRequestObject

	request.Params = params

	var body PostAuthPasswordChangeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthPasswordChange(ctx, request.(PostAuthPasswordChangeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthPasswordChange")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAuthPasswordChangeResponseObject); ok {
		if err := validResponse.VisitPostAuthPasswordChangeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuthPasswordReset operation middleware
func (sh *strictHandler) PostAuthPasswordReset(w http.ResponseWriter, r *http.Request) {
	var request PostAuthPasswordResetRequestObject

	var body PostAuthPasswordResetJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthPasswordReset(ctx, request.(PostAuthPasswordResetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthPasswordReset")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAuthPasswordResetResponseObject); ok {
		if err := validResponse.VisitPostAuthPasswordResetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuthPasswordResetRequest operation middleware
func (sh *strictHandler) PostAuthPasswordResetRequest(w http.ResponseWriter, r *http.Request) {
	var request PostAuthPasswordResetRequestRequestObject

	var body PostAuthPasswordResetRequestJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthPasswordResetRequest(ctx, request.(PostAuthPasswordResetRequestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthPasswordResetRequest")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAuthPasswordResetRequestResponseObject); ok {
		if err := validResponse.VisitPostAuthPasswordResetRequestResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuthRegister operation middleware
func (sh *strictHandler) PostAuthRegister(w http.ResponseWriter, r *http.Request) {
	var request PostAuthRegisterRequestObject

	var body PostAuthRegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthRegister(ctx, request.(PostAuthRegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthRegister")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAuthRegisterResponseObject); ok {
		if err := validResponse.VisitPostAuthRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDelay operation middleware
func (sh *strictHandler) GetDelay(w http.ResponseWriter, r *http.Request, seconds float64) {
	var request GetDelayRequestObject

	request.Seconds = seconds

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDelay(ctx, request.(GetDelayRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDelay")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDelayResponseObject); ok {
		if err := validResponse.VisitGetDelayResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteEcho operation middleware
func (sh *strictHandler) DeleteEcho(w http.ResponseWriter, r *http.Request) {
	var request DeleteEchoRequestObject

	data, err := io.ReadAll(r.Body)
	if err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't read body: %w", err))
		return
	}
	if len(data) > 0 {
		body := DeleteEchoTextRequestBody(data)
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteEcho(ctx, request.(DeleteEchoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteEcho")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteEchoResponseObject); ok {
		if err := validResponse.VisitDeleteEchoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetEcho operation middleware
func (sh *strictHandler) GetEcho(w http.ResponseWriter, r *http.Request) {
	var request GetEchoRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEcho(ctx, request.(GetEchoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEcho")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEchoResponseObject); ok {
		if err := validResponse.VisitGetEchoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchEcho operation middleware
func (sh *strictHandler) PatchEcho(w http.ResponseWriter, r *http.Request) {
	var request PatchEchoRequestObject

	data, err := io.ReadAll(r.Body)
	if err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't read body: %w", err))
		return
	}
	if len(data) > 0 {
		body := PatchEchoTextRequestBody(data)
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchEcho(ctx, request.(PatchEchoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchEcho")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchEchoResponseObject); ok {
		if err := validResponse.VisitPatchEchoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostEcho operation middleware
func (sh *strictHandler) PostEcho(w http.ResponseWriter, r *http.Request) {
	var request PostEchoRequestObject

	data, err := io.ReadAll(r.Body)
	if err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't read body: %w", err))
		return
	}
	if len(data) > 0 {
		body := PostEchoTextRequestBody(data)
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostEcho(ctx, request.(PostEchoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostEcho")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostEchoResponseObject); ok {
		if err := validResponse.VisitPostEchoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutEcho operation middleware
func (sh *strictHandler) PutEcho(w http.ResponseWriter, r *http.Request) {
	var request PutEchoRequestObject

	data, err := io.ReadAll(r.Body)
	if err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't read body: %w", err))
		return
	}
	if len(data) > 0 {
		body := PutEchoTextRequestBody(data)
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutEcho(ctx, request.(PutEchoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutEcho")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutEchoResponseObject); ok {
		if err := validResponse.VisitPutEchoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHeaders operation middleware
func (sh *strictHandler) GetHeaders(w http.ResponseWriter, r *http.Request) {
	var request GetHeadersRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHeaders(ctx, request.(GetHeadersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHeaders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHeadersResponseObject); ok {
		if err := validResponse.VisitGetHeadersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetIp operation middleware
func (sh *strictHandler) GetIp(w http.ResponseWriter, r *http.Request) {
	var request GetIpRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetIp(ctx, request.(GetIpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetIp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetIpResponseObject); ok {
		if err := validResponse.VisitGetIpResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLivez operation middleware
func (sh *strictHandler) GetLivez(w http.ResponseWriter, r *http.Request) {
	var request GetLivezRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLivez(ctx, request.(GetLivezRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLivez")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLivezResponseObject); ok {
		if err := validResponse.VisitGetLivezResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadyz operation middleware
func (sh *strictHandler) GetReadyz(w http.ResponseWriter, r *http.Request) {
	var request GetReadyzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadyz(ctx, request.(GetReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadyz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadyzResponseObject); ok {
		if err := validResponse.VisitGetReadyzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetScheme operation middleware
func (sh *strictHandler) GetScheme(w http.ResponseWriter, r *http.Request) {
	var request GetSchemeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetScheme(ctx, request.(GetSchemeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetScheme")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSchemeResponseObject); ok {
		if err := validResponse.VisitGetSchemeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetStartupz operation middleware
func (sh *strictHandler) GetStartupz(w http.ResponseWriter, r *http.Request) {
	var request GetStartupzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetStartupz(ctx, request.(GetStartupzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStartupz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetStartupzResponseObject); ok {
		if err := validResponse.VisitGetStartupzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetStatus operation middleware
func (sh *strictHandler) GetStatus(w http.ResponseWriter, r *http.Request, code int32) {
	var request GetStatusRequestObject

	request.Code = code

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetStatus(ctx, request.(GetStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetStatusResponseObject); ok {
		if err := validResponse.VisitGetStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUserAgent operation middleware
func (sh *strictHandler) GetUserAgent(w http.ResponseWriter, r *http.Request) {
	var request GetUserAgentRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserAgent(ctx, request.(GetUserAgentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserAgent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUserAgentResponseObject); ok {
		if err := validResponse.VisitGetUserAgentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUuid operation middleware
func (sh *strictHandler) GetUuid(w http.ResponseWriter, r *http.Request) {
	var request GetUuidRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUuid(ctx, request.(GetUuidRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUuid")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUuidResponseObject); ok {
		if err := validResponse.VisitGetUuidResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVersion operation middleware
func (sh *strictHandler) GetVersion(w http.ResponseWriter, r *http.Request) {
	var request GetVersionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVersion(ctx, request.(GetVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVersion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVersionResponseObject); ok {
		if err := validResponse.VisitGetVersionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Hx7bxu3svhXIfb3A5oCK1mynZfzl/M4qe9xWtdxew5ObxBQy5GWx7vkluTKUQN/9wsOue9dSVYsJ0UL",
	"BIi8yyXnPcPhDD8HkUwzKUAYHZx8DjKqaAoGFP71Sqv5lbwG8QNQBso+YqAjxTPDpQhOgqsYyKv3l/8g",
	"xo4icyVTYmIgDJYy0zMuPkZazUkk5TWHMbmE33OugBEuSKZoZHgERAqiDTUwimIqFlwsiILfc9BGEyMJ",
	"zU0MwvCIGmBEydyAfkEoSbnWdqxU9mdKTRQD82CsOCRME0qOJ0dEgc6k0DAm73JtCI5EGN3YmcyF/Q4f",
	"RblSIAzRoDWXYvy/IggD+ETTLIHgJHg+n0aH9OnsCRyz4/mEPouOZlN2CI/nT+jT2bMoCANuqRI7aoWB",
	"oKn97t8jS6MRUjIIAx3FkFJLTLPK7HttFBeL4Pb2Ngw87i8l44A8eBPF8qVkK/s7ksKAMPgpfDIHWULt",
	"gp9rU1bQxpAkMgj7Fmky8VQQib9pUpCezCRbWaoomCcQGTKj0fWYWHbjG66JAsoI1QRhIBYcQgUjEMUS",
	"GFmCmlHD05DkmZ3nyTH5J39pCeqQdDxpIHgl5TlVC2ghSrMssdznUhz8V8sWuv9fwTw4Cf7fQSXGB+6t",
	"PnijlFSXfqk+xC06DYThUwTANMpCSj/xNE+J5n8AMTE1JKKCzMBjOA5uQwT90lGIO8juB3Ccdhju04It",
	"XAoi5wguF5FMa8ozRkL7Ge2CryGhq3JWCx9j3HH9QskMlEGBm9NEQxhktUdW6RO66td+kaczUBYKDZEU",
	"nngFg8kN1QS/thSr6dI0DOZSpdQEJwGT+SyBSlLdlEGhDdZgBCe/eSA+lMPk7L8QGcuG15CBYCCi1asY",
	"ous7IpeC1tSJXaU8rJzSynoMNDHxqqtMYWBNV47zgMhTC6e8toha2bO6fs2zDJgFu5ocR7TVsomsn7YP",
	"24Z03A3Vmbcjm9TA6bDV+VKRx+THPEnI3NpbMLFERqNSKLUiQrovH+k8iq1VePvm6vu2+SwMksiThFqO",
	"nxiVQw9Nnf3Um9TEOaV3NLPfOKCaTHz75qqPZVLxhTObXTpENElAfaeJG0TOLghlTIHWDfENDidH48l4",
	"Oj0aHx/2rZFREzeBOaAZP1hODyxx+774PQe1uhPK+BD68XDvyKPYmMz6SPu//n7YWISl+NqRQYj/6abY",
	"ukebJNczwpOgwKtiakn/EoFeIW/Y7rtJudO9DllOSZynVIys47LiR2qvC8Lgp01OO00kkWRAUhtBzCz9",
	"nJWjYgFkOpmMHj9/vpEwDqw+ZCuuDiL6OeAGUt0TNJTzUaXoKuhxFinNMgyV5sQGJNpHO1yRhGtjHy9p",
	"koMOSa6BoYrPpInJD1dXF8SzDX07spJUISJ5BDSKSUpXhGYZUEVSqdBZCiJFBG0L8Dk4jSLIjKVGxzt+",
	"CINfNKjR6QL9529BlKvk4Nn46XgafLgdpJreUUjubmNa7Cwm6GPoWbYjVPs3TS0s/IJ9SJzzJfyxIx69",
	"XvEefeC5XHBx6YzXHUHLqNY3UrF+ItMokrkwpBjVJC1NeAT2VVALX8oJe4x6rkG5TcC6xYpRPYttJFK5",
	"QlgB0kexdy7K2ZGftRhpg1Gl0bWQNwmwBaQgTBOlCw8hiakmMwBhA0XAQZucilu/D7Ni0ld2+wi7CYXf",
	"+F1sIxvf6XKfWFA8JApGS1B8zm3cBHNnBoHglha+UIgE3KwHTMBNCQp5pI20W2wpkpWNxCiZRWqVGUvz",
	"+PsBUA4HYEnpp3MQCxvLTA+fhUHKRfH3s008a9O0icg6Tl5aodiNkX8WWoUBph8GgjcuFgmMcg1OP3yq",
	"gmudW/FakQOam/igWPsAB43qsVwJ9dOfV0c3z/5zPc2uJuLlYXR5rH998un0OXvzeP52Gv/P0fX50/TH",
	"SfbzRhU0PnuxCxN34+V641m8tdEMUobQBrXm7UDujvZ0C9y+pik9cwGrBZfAJ66NDlsEKG2sk5txcB9C",
	"GJLM/iWM05mbGEQbjjE5EyRTkuUuQWFirsmNzBOG2ZOU8gQzgNoAZTb6VGByJYC194v3J7vr3MclULba",
	"Nc6JYoiu9bqwfV1w2c5b3DZi5ZQvFMbHjYjKBk52fym1WSjoe6WA8e7zvgi6G6VZ2bObNSHNR/e7EbQV",
	"r7eK28KCOv1UX3BtQD1EDLebmb8fK7/Bhgn+e14zZXbrZbyT8lj027AaFEeHDSCO7itgfI+b813j/28y",
	"NbEm3/DeUGXy7Fu0A5EUc77oUfQ1BmI7bdcWabBSjb8syT60Uh/+/Zcr/Hscsyt5JRsQJsxR1FM0pTOp",
	"683hZFLTZi7MUW1nzIWBBahO5qR/Dy6k4BEelFAtBcliRXWluDVIQsLnxDpw0VThn/65kZ6Ibh8Rf9Gg",
	"MD+yIx2t7o/owh9QVDDVUi3bmA8/xRCEOwLH2XCg950ubCVnIIzdZ7Wiu8n02fw5ezIbRbPZfPR0dshG",
	"z2eP2YjOnrH5bMaOZyjIpRDkOe/dbCmZwFo47IC6UbKPgzCgLHV5lAok/+auPsGj+wU5AcSsZucRp15u",
	"5ZztKkp5H79OiaKCyTRZkQUIUHhouwSlbSB4TH755ex1E6HpzDItYqPZbM5GxzuyrS2jdlAfvr86SHY9",
	"Pcl5wj4anrbOig4nh09GE/vvajo5mdh//6nDzKiBEX7WIwwLbj7quHV0S2fR9PCod7j86MnZ/GIhp+PD",
	"4/Fx7xEVqKUVm9YBlz+hH9GM933Vu8xkPB1PNvsDv2A1SYVnWCdjA58uw+y8XMxlV87eccFTmpCfMhCn",
	"F2fEeSpFdAYRGuPXsPwp0y+5ICoXdi0CgmWSC4PZUsMN4lMNO704q8FbYHobBjIDYUl0EhyNJ+Mjf7CB",
	"AuG24Yn0KVsbk3dB/dWlhdy5aKQA7RdNXEbdTm5/tcocfP3BSfMsVYNxs/jXOANWX7j6Cj0mp0TnUQRa",
	"z/OEIGBESUMNND4McUtogyxK5gp0XM7IWTUp7vfcnsxqAUYaZyw4CS6kNqe5iTEJG9RLFlb3dgTeSPDe",
	"NgXMqBzaRQSHk8m9rd3wYQNlA3VG3oACsqSJJx4tqXlDNXIYmCudGOIboQq5S5ackvdgRq9cvQzSvnZQ",
	"Ub3qitn7jcKxvvLkNgyO75GGd6+94LpR00MTaz99ncXxZPqwkJU7MqmqbSTXuDtRCiLjwDo8ekCwpCQp",
	"FSsydwkUp93UGEgzo52AFTtfqUiUcBDGwmwHSEUVT1YkkdE1sBc2SlYrQufWZlqhyUBxyQgXzFug2Qqf",
	"X9pxo1Mc5wSxI5S1IX1S6WtCJLmh3BSpcVyei0VTJjcG6E5MdZ6mVK2Ck+BcLggX5IabuOKYlft6Np0u",
	"tPVJ1mAFH+z3pdWWuRk2268hgcJstsrCcIkoAao2mWNf76YJ9fahGOpGeHOBJWlW7ut1Yg1yD9pfi0LY",
	"KNr7rV/MqiEH7aK+2w8dW3o8sHOv2TWG9HEWbx0RnHVEatlQcHcD92oLgm9h4h7QkPwoW1znusieeqt2",
	"9LBWrVap2bS2TIImQtarI4sSyKCrcjI3RbampRlr9M0FzQvoUbVL3LLrKo9MtZYRRzuEut1XmrlJt/oU",
	"5y2g3rzDPdFXjR48Ms2oz+L+8O5uvZQ2mO8Y1WBHF4M1MlAeWLlj0W1j5tZhK6o9xsIUE6VSVPmXHoKS",
	"n0QRFDeMB9c+NGbk0cYwGCM0f/7WtGHfOyOeJESa2O5A3BS6BMlJNDq9pby2oeB+vULzOPyevMP9B/j9",
	"p/bfYKRfip31ek5wu17PvvPStEWorwDF7cv84aWf5O+o/29nXe7rvc3pmMzG1sUX4Vd23elg40ufhdwi",
	"kG5WIQzb9FdS6DxFqzdQ39Cy6yXwpXGvwgJn2a/KLg7ED/mHr6WwIyrLXJ2Vf6crC103ylsYVDz0D/Zr",
	"DRuVLw9sDNsVYtvYQ1++9W2bkemDQ1av2SG5wFOgkMCnzHIStZQmeJaOFbfdMMt+TytK59rl6moTb62Q",
	"RVnQsGKe2bCmqZYeVrtqMduoVVuDGrXgSxDVUQW5koQuJWckAXptv76JeVTtzbWrEAmbaU2uCU1u6EqT",
	"w8mEKFhQxRIbrck5uYkBo6qNJSaFIWjXmbzwsHK7Y00l4cb1LrlDwrKQu4AFham3qGVbA1Eo78PZia9k",
	"LvproTYoq7UZFGvAbaD0rx5Ct6uYnOdKctblFjqyb9fytHTafUN7FWqNNitfKLPGsSrABD91ZCx3zE3l",
	"bOTF9nX24E9hijQk1yRC4FijsgXB9LzUWMGnqNAUVXmdnhU1Q3vSrXZJ0lb6NH3QvYhjMK3I+vd5w552",
	"Hs+/0nkDOkMXGhh6DaJrR5yQ+hh5OOGC3ZIHn31T5u1g8u1flJsqWeEpBKynr7PM3VtUGBcLJ2S4EKo6",
	"zTIrkoZMJ8VHL0hC1QKU7zBCwYsSmmZQ9VzTbEx+hAU1fAnFOOzgxgbuSa2B2y6Hxwj2EURGlxyNqIgg",
	"SZA/tc25WrqSDT/K8BRkbgZSg9gg282XbNXyKj0ZHk1G0wlWFGIjuG+B823gfnTQtiphX/t2b4Os70kO",
	"TqYTLPpzf0y6nbMf9uj4m43EwzGwcxzVGVMlW0irr7prKICwciu87LVVDfFshYcrQr1f7QhBTQ3PqQER",
	"rbwmYsOna6IGA8PpbwaG8kQPFUKeuFo3114ZEitaYacjLyz69cJul1joKy9DVJC6LexTCHf+9cY1q7bc",
	"bR8XGvcWHJSXFgxEoP0z+HEHrbZ63MMdbfdZ4yKBJj/t617K1jh3JtCwYMPh2rOK/TMLsyHIsAF7VfJm",
	"T3p+j7cQ7MyDjJoo/rOozIUF9q+sMf37k2+UWVKbvzSv8j8Pq/K/MKdsBFHbkm08QG807SuIgC/rx+i1",
	"roqOQ/mhvKFhbz6l3bO/YaPm8Rj0Iq1xgwTk2Va068jpuqaUDvnOsn1SrnalwFBRwZr7AYbP8YuPqtGD",
	"VEz4Ev4YJOSFkhFoPcImKztUWAJiR8iYvJZ4YoV/kQvXu/b+53O7874EhjfsKOilKt5CsE/CNq856KGt",
	"R8xtzXv2CecFrpmSM6hR79JVHnvq4aZ+mHzY+aMbCe8aTsWFW/5OLtRqYhSdz3nUSzbX1bhPurX6JvsC",
	"xB74cdf3+B7PUu8MhpXDApSWVlDGt2Bk1du20aDcsdWtSogXho0qxZd4xK9kvogJJUbluH3NlPy0Cuur",
	"cO1SRtUtfP8e/UOqG6oYsNGFkkZ6Q/nC1arccA0Esyno4urCx7XPnhADKuUCk41X5+/LRFEkhYDBjO1b",
	"MK59cJ8C2GpQ3OBK/FZq2BI2Bw4aQe0bBbdV5LoS+2+xM9sihBWUvepbtCPulX7tlscNulNAzyvg712b",
	"vwAmbXiSuIsl5aLP6/m5N2k3dvAdfI4kg9s1So5JUF0FVp1GxEzJJa+dWtko2aUwG1dJFTVgne/77ph6",
	"QahY+UIzzJTWr7qcNA7G+oXKtWluzHB2gEGvg6ryyIMylOTE3sWtMpz9TZllivPx8+e1HOd0MumpB2+n",
	"Ob9iOrHBOk1kbjRnrqbGMVi5m2BwmjnNE3OfSlNvrR0AtadTtoDdF/u7WHDARBZ5z/Y0NUXy8uX0qNlq",
	"utFTVld/eR91x71L2Rm779LeZvvtBqdTYTW4hekgPuh5io7LtbSk2zVgdunn+ir3R7p6p2l/MhHhRgiX",
	"x21yvfW4lPjhuEFS1XoXPbU6CP9adibuDed2t2kP2n4IScFQRg1t4/0y54k75V22RvY7MN/t2W/ZTy/O",
	"yHJKZlQ7bxSEQa6S6mpKrPX1k3bky60R+qtQnRN16Rvs5yzhavZZeqdQQHgbduUWNWVUSyWXE7gLRsFq",
	"Cl5FuiErVVuvkIbuem+ak6vCuDnbN7KfuUu82nauNru3cxsn58JgiRJgkYUyfM4jTpPQ3TkNrDpX8gdi",
	"5QrFAVJ3CXccPyoP3avSDazZcNUiTtJD1yKG/8nchOW5qK/xLCdBXo7J+4FLuKXovYSbeBdfqz/Yun6d",
	"PHJHmiOdz1JuXN1ApqRxIuDvjfTEwEPt2w+3/xcAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
