// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Defines values for DependencyCheckStatus.
const (
	DependencyCheckStatusError   DependencyCheckStatus = "error"
	DependencyCheckStatusOk      DependencyCheckStatus = "ok"
	DependencyCheckStatusSkipped DependencyCheckStatus = "skipped"
)

// Valid indicates whether the value is a known member of the DependencyCheckStatus enum.
func (e DependencyCheckStatus) Valid() bool {
	switch e {
	case DependencyCheckStatusError:
		return true
	case DependencyCheckStatusOk:
		return true
	case DependencyCheckStatusSkipped:
		return true
	default:
		return false
	}
}

// Defines values for LivezResponseStatus.
const (
	LivezResponseStatusOk LivezResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the LivezResponseStatus enum.
func (e LivezResponseStatus) Valid() bool {
	switch e {
	case LivezResponseStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for ReadyzResponseStatus.
const (
	NotReady ReadyzResponseStatus = "not_ready"
	Ready    ReadyzResponseStatus = "ready"
)

// Valid indicates whether the value is a known member of the ReadyzResponseStatus enum.
func (e ReadyzResponseStatus) Valid() bool {
	switch e {
	case NotReady:
		return true
	case Ready:
		return true
	default:
		return false
	}
}

// Defines values for StartupzResponseStatus.
const (
	Started  StartupzResponseStatus = "started"
	Starting StartupzResponseStatus = "starting"
)

// Valid indicates whether the value is a known member of the StartupzResponseStatus enum.
func (e StartupzResponseStatus) Valid() bool {
	switch e {
	case Started:
		return true
	case Starting:
		return true
	default:
		return false
	}
}

// DependencyCheck defines model for DependencyCheck.
type DependencyCheck struct {
	Message *string               `json:"message,omitempty"`
	Status  DependencyCheckStatus `json:"status"`
}

// DependencyCheckStatus defines model for DependencyCheck.Status.
type DependencyCheckStatus string

// LivezResponse defines model for LivezResponse.
type LivezResponse struct {
	Status LivezResponseStatus `json:"status"`
}

// LivezResponseStatus defines model for LivezResponse.Status.
type LivezResponseStatus string

// ReadyzResponse defines model for ReadyzResponse.
type ReadyzResponse struct {
	Checks map[string]DependencyCheck `json:"checks"`
	Status ReadyzResponseStatus       `json:"status"`
}

// ReadyzResponseStatus defines model for ReadyzResponse.Status.
type ReadyzResponseStatus string

// StartupzResponse defines model for StartupzResponse.
type StartupzResponse struct {
	Checks map[string]DependencyCheck `json:"checks"`
	Status StartupzResponseStatus     `json:"status"`
}

// StartupzResponseStatus defines model for StartupzResponse.Status.
type StartupzResponseStatus string

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	BuildTime time.Time `json:"build_time"`
	GitSha    string    `json:"git_sha"`
	GoVersion string    `json:"go_version"`
	Service   string    `json:"service"`
	Version   string    `json:"version"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness probe
	// (GET /livez)
	GetLivez(w http.ResponseWriter, r *http.Request)
	// Readiness probe
	// (GET /readyz)
	GetReadyz(w http.ResponseWriter, r *http.Request)
	// Startup probe
	// (GET /startupz)
	GetStartupz(w http.ResponseWriter, r *http.Request)
	// Build and version metadata
	// (GET /version)
	GetVersion(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Liveness probe
// (GET /livez)
func (_ Unimplemented) GetLivez(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Readiness probe
// (GET /readyz)
func (_ Unimplemented) GetReadyz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Startup probe
// (GET /startupz)
func (_ Unimplemented) GetStartupz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Build and version metadata
// (GET /version)
func (_ Unimplemented) GetVersion(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetLivez operation middleware
func (siw *ServerInterfaceWrapper) GetLivez(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLivez(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStartupz operation middleware
func (siw *ServerInterfaceWrapper) GetStartupz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStartupz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/livez", wrapper.GetLivez)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.GetReadyz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/startupz", wrapper.GetStartupz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/version", wrapper.GetVersion)
	})

	return r
}

type GetLivezRequestObject struct {
}

type GetLivezResponseObject interface {
	VisitGetLivezResponse(w http.ResponseWriter) error
}

type GetLivez200JSONResponse LivezResponse

func (response GetLivez200JSONResponse) VisitGetLivezResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyzRequestObject struct {
}

type GetReadyzResponseObject interface {
	VisitGetReadyzResponse(w http.ResponseWriter) error
}

type GetReadyz200JSONResponse ReadyzResponse

func (response GetReadyz200JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyz503JSONResponse ReadyzResponse

func (response GetReadyz503JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetStartupzRequestObject struct {
}

type GetStartupzResponseObject interface {
	VisitGetStartupzResponse(w http.ResponseWriter) error
}

type GetStartupz200JSONResponse StartupzResponse

func (response GetStartupz200JSONResponse) VisitGetStartupzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetStartupz503JSONResponse StartupzResponse

func (response GetStartupz503JSONResponse) VisitGetStartupzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetVersionRequestObject struct {
}

type GetVersionResponseObject interface {
	VisitGetVersionResponse(w http.ResponseWriter) error
}

type GetVersion200JSONResponse VersionResponse

func (response GetVersion200JSONResponse) VisitGetVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Liveness probe
	// (GET /livez)
	GetLivez(ctx context.Context, request GetLivezRequestObject) (GetLivezResponseObject, error)
	// Readiness probe
	// (GET /readyz)
	GetReadyz(ctx context.Context, request GetReadyzRequestObject) (GetReadyzResponseObject, error)
	// Startup probe
	// (GET /startupz)
	GetStartupz(ctx context.Context, request GetStartupzRequestObject) (GetStartupzResponseObject, error)
	// Build and version metadata
	// (GET /version)
	GetVersion(ctx context.Context, request GetVersionRequestObject) (GetVersionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetLivez operation middleware
func (sh *strictHandler) GetLivez(w http.ResponseWriter, r *http.Request) {
	var request GetLivezRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLivez(ctx, request.(GetLivezRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLivez")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLivezResponseObject); ok {
		if err := validResponse.VisitGetLivezResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadyz operation middleware
func (sh *strictHandler) GetReadyz(w http.ResponseWriter, r *http.Request) {
	var request GetReadyzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadyz(ctx, request.(GetReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadyz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadyzResponseObject); ok {
		if err := validResponse.VisitGetReadyzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetStartupz operation middleware
func (sh *strictHandler) GetStartupz(w http.ResponseWriter, r *http.Request) {
	var request GetStartupzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetStartupz(ctx, request.(GetStartupzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStartupz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetStartupzResponseObject); ok {
		if err := validResponse.VisitGetStartupzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVersion operation middleware
func (sh *strictHandler) GetVersion(w http.ResponseWriter, r *http.Request) {
	var request GetVersionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVersion(ctx, request.(GetVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVersion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVersionResponseObject); ok {
		if err := validResponse.VisitGetVersionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFdNb+M2EP0rxLRHRZadbQ+6ZRugCLDFutliDy2MgJbGEjcSyXJota6h/14MJX9I1jbpboIW8IERh8M3",
	"743mKXvITG2NRu0J0j1QVmItw/IWLeocdbb7ocTskR/JPFdeGS2rpTMWnVdIkG5kRRiBPXu0hxqJZIG8",
	"xD9lbSuEFPJjSqFIlCgrX+4gAr+zvE3eKV1AGwF56bchD+ptDelvYB4hAnTOOIiAHpW1mMMqOkseIkaZ",
	"2ggc/r5VDnNO0qddHePM+hNmnm98pxr86x7JGk34L2udRPuC2O5R5rsvBZexePT5Q3v41uEGUvhmdmqF",
	"Wd8Hs3ETtGdV7aFWhZOcckADV9tGYA35wuHUlsNcXT5vJ0q/pNYxGRCBNv6hWw+YPmw/i+zowM4U6x+8",
	"dH5r/4+8Z0ZvVDFB7D8I8jx2iYvGHKJuxdwN6D3tfz3BH9GRMvoL+V1vVZU/eFWPZswiWXx/lfDvl3mS",
	"Jvz7FSLYGFdLzzNIerwKxybmTqH8A5VymFGus/niejLcPDRdEcMThZnHizfxm8nRhq5R2cVgbIyltdJX",
	"0qqpU5PXJPE8Tp6Wor/wlORUZ3RO46CeS8E4r9IbwxhypMwp6wMk+ElpVctKvLeob5Z3omsSJ8hiJjbG",
	"iVts3lt6q7RwW813CdS5NUp7ihm/8qGeU9jN8u4M76HSNgJjUTNFKVzHScyiWOnL0BCzikc4rwr0lyCX",
	"zmRIdGV0tRMcqpFIhPaMxa0R2vjuL7HsBteHn98J48Q9zypRokOGyh0YXrC7HFL4EX3wDWDGuy4OUBZJ",
	"0r+mHnXAIq2tVBZOzj5RJ2T3rj81CYbGFFSYLIwdVXJdcegA2ta1dDtIg7OFWq0z69D1siBujPtOC1hx",
	"/CwMzs/TF8YQiT9K9CU64UsUZzXx5SGB8EY4zFA1KLyTm43KJmnrLO01eRuZ5gRxNxP4Y26y75Lr/w4G",
	"9+EBykBHzqSeIST1vvVcKc9l7M+KUpLgYir0mE8KeHDH15TwwoGfYO+AXp3Av7ieX4GJvKoqoTTrxx9G",
	"NFa4z/2EvmdW0Mt7Ic7H46B/NW3G5j1BQx8iavQyl16Oy33L1iOkzkUzipyuvTdPdLwxbmr2nWYu1pJQ",
	"sCVABFtXQQozadWsmUO7OiYdn+3viPr/SDr+o4As2OMR19C2tORvjyPCdtX+HQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
