// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for DependencyCheckStatus.
const (
	DependencyCheckStatusError   DependencyCheckStatus = "error"
	DependencyCheckStatusOk      DependencyCheckStatus = "ok"
	DependencyCheckStatusSkipped DependencyCheckStatus = "skipped"
)

// Valid indicates whether the value is a known member of the DependencyCheckStatus enum.
func (e DependencyCheckStatus) Valid() bool {
	switch e {
	case DependencyCheckStatusError:
		return true
	case DependencyCheckStatusOk:
		return true
	case DependencyCheckStatusSkipped:
		return true
	default:
		return false
	}
}

// Defines values for EchoResponseScheme.
const (
	EchoResponseSchemeHttp  EchoResponseScheme = "http"
	EchoResponseSchemeHttps EchoResponseScheme = "https"
)

// Valid indicates whether the value is a known member of the EchoResponseScheme enum.
func (e EchoResponseScheme) Valid() bool {
	switch e {
	case EchoResponseSchemeHttp:
		return true
	case EchoResponseSchemeHttps:
		return true
	default:
		return false
	}
}

// Defines values for LivezResponseStatus.
const (
	LivezResponseStatusOk LivezResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the LivezResponseStatus enum.
func (e LivezResponseStatus) Valid() bool {
	switch e {
	case LivezResponseStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for ReadyzResponseStatus.
const (
	NotReady ReadyzResponseStatus = "not_ready"
	Ready    ReadyzResponseStatus = "ready"
)

// Valid indicates whether the value is a known member of the ReadyzResponseStatus enum.
func (e ReadyzResponseStatus) Valid() bool {
	switch e {
	case NotReady:
		return true
	case Ready:
		return true
	default:
		return false
	}
}

// Defines values for SchemeResponseScheme.
const (
	SchemeResponseSchemeHttp  SchemeResponseScheme = "http"
	SchemeResponseSchemeHttps SchemeResponseScheme = "https"
)

// Valid indicates whether the value is a known member of the SchemeResponseScheme enum.
func (e SchemeResponseScheme) Valid() bool {
	switch e {
	case SchemeResponseSchemeHttp:
		return true
	case SchemeResponseSchemeHttps:
		return true
	default:
		return false
	}
}

// Defines values for StartupzResponseStatus.
const (
	Started  StartupzResponseStatus = "started"
	Starting StartupzResponseStatus = "starting"
)

// Valid indicates whether the value is a known member of the StartupzResponseStatus enum.
func (e StartupzResponseStatus) Valid() bool {
	switch e {
	case Started:
		return true
	case Starting:
		return true
	default:
		return false
	}
}

// DelayResponse defines model for DelayResponse.
type DelayResponse struct {
	// Delay The number of seconds the response was delayed.
	Delay float64 `json:"delay"`
}

// DependencyCheck defines model for DependencyCheck.
type DependencyCheck struct {
	Message *string               `json:"message,omitempty"`
	Status  DependencyCheckStatus `json:"status"`
}

// DependencyCheckStatus defines model for DependencyCheck.Status.
type DependencyCheckStatus string

// EchoResponse defines model for EchoResponse.
type EchoResponse struct {
	// Body The request body echoed back verbatim. Null for methods that carry no body (such as GET).
	Body *string `json:"body,omitempty"`

	// Headers A mapping of names to their list of values, used for both HTTP headers and query parameters (each may appear more than once).
	Headers HeaderMap `json:"headers"`
	Method  string    `json:"method"`

	// Origin The caller's origin IP address.
	Origin string `json:"origin"`
	Path   string `json:"path"`

	// Query A mapping of names to their list of values, used for both HTTP headers and query parameters (each may appear more than once).
	Query HeaderMap `json:"query"`

	// Scheme The scheme (http or https) of the incoming request.
	Scheme EchoResponseScheme `json:"scheme"`
}

// EchoResponseScheme The scheme (http or https) of the incoming request.
type EchoResponseScheme string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error A human-readable description of the error.
	Error string `json:"error"`
}

// HeaderMap A mapping of names to their list of values, used for both HTTP headers and query parameters (each may appear more than once).
type HeaderMap map[string][]string

// HeadersResponse defines model for HeadersResponse.
type HeadersResponse struct {
	// Headers A mapping of names to their list of values, used for both HTTP headers and query parameters (each may appear more than once).
	Headers HeaderMap `json:"headers"`
}

// IpResponse defines model for IpResponse.
type IpResponse struct {
	// Origin The caller's origin IP address.
	Origin string `json:"origin"`
}

// LivezResponse defines model for LivezResponse.
type LivezResponse struct {
	Status LivezResponseStatus `json:"status"`
}

// LivezResponseStatus defines model for LivezResponse.Status.
type LivezResponseStatus string

// ReadyzResponse defines model for ReadyzResponse.
type ReadyzResponse struct {
	Checks map[string]DependencyCheck `json:"checks"`
	Status ReadyzResponseStatus       `json:"status"`
}

// ReadyzResponseStatus defines model for ReadyzResponse.Status.
type ReadyzResponseStatus string

// SchemeResponse defines model for SchemeResponse.
type SchemeResponse struct {
	// Scheme The scheme (http or https) of the incoming request.
	Scheme SchemeResponseScheme `json:"scheme"`
}

// SchemeResponseScheme The scheme (http or https) of the incoming request.
type SchemeResponseScheme string

// StartupzResponse defines model for StartupzResponse.
type StartupzResponse struct {
	Checks map[string]DependencyCheck `json:"checks"`
	Status StartupzResponseStatus     `json:"status"`
}

// StartupzResponseStatus defines model for StartupzResponse.Status.
type StartupzResponseStatus string

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	// Code The HTTP status code returned.
	Code int32 `json:"code"`

	// Description The canonical reason phrase for the status code, if known.
	Description *string `json:"description,omitempty"`
}

// UserAgentResponse defines model for UserAgentResponse.
type UserAgentResponse struct {
	UserAgent string `json:"user-agent"`
}

// UuidResponse defines model for UuidResponse.
type UuidResponse struct {
	// Uuid A randomly generated version 4 UUID.
	Uuid openapi_types.UUID `json:"uuid"`
}

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	BuildTime time.Time `json:"build_time"`
	GitSha    string    `json:"git_sha"`
	GoVersion string    `json:"go_version"`
	Service   string    `json:"service"`
	Version   string    `json:"version"`
}

// EchoBodyTooLarge defines model for EchoBodyTooLarge.
type EchoBodyTooLarge = ErrorResponse

// EchoReflection defines model for EchoReflection.
type EchoReflection = EchoResponse

// DeleteEchoTextBody defines parameters for DeleteEcho.
type DeleteEchoTextBody = string

// PatchEchoTextBody defines parameters for PatchEcho.
type PatchEchoTextBody = string

// PostEchoTextBody defines parameters for PostEcho.
type PostEchoTextBody = string

// PutEchoTextBody defines parameters for PutEcho.
type PutEchoTextBody = string

// DeleteEchoTextRequestBody defines body for DeleteEcho for text/plain ContentType.
type DeleteEchoTextRequestBody = DeleteEchoTextBody

// PatchEchoTextRequestBody defines body for PatchEcho for text/plain ContentType.
type PatchEchoTextRequestBody = PatchEchoTextBody

// PostEchoTextRequestBody defines body for PostEcho for text/plain ContentType.
type PostEchoTextRequestBody = PostEchoTextBody

// PutEchoTextRequestBody defines body for PutEcho for text/plain ContentType.
type PutEchoTextRequestBody = PutEchoTextBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Delay the response by a given number of seconds
	// (GET /delay/{seconds})
	GetDelay(w http.ResponseWriter, r *http.Request, seconds float64)
	// Echo the incoming request
	// (DELETE /echo)
	DeleteEcho(w http.ResponseWriter, r *http.Request)
	// Echo the incoming request
	// (GET /echo)
	GetEcho(w http.ResponseWriter, r *http.Request)
	// Echo the incoming request
	// (PATCH /echo)
	PatchEcho(w http.ResponseWriter, r *http.Request)
	// Echo the incoming request
	// (POST /echo)
	PostEcho(w http.ResponseWriter, r *http.Request)
	// Echo the incoming request
	// (PUT /echo)
	PutEcho(w http.ResponseWriter, r *http.Request)
	// Echo the request headers
	// (GET /headers)
	GetHeaders(w http.ResponseWriter, r *http.Request)
	// Return the caller's IP address
	// (GET /ip)
	GetIp(w http.ResponseWriter, r *http.Request)
	// Liveness probe
	// (GET /livez)
	GetLivez(w http.ResponseWriter, r *http.Request)
	// Readiness probe
	// (GET /readyz)
	GetReadyz(w http.ResponseWriter, r *http.Request)
	// Return the request scheme
	// (GET /scheme)
	GetScheme(w http.ResponseWriter, r *http.Request)
	// Startup probe
	// (GET /startupz)
	GetStartupz(w http.ResponseWriter, r *http.Request)
	// Return a given HTTP status code
	// (GET /status/{code})
	GetStatus(w http.ResponseWriter, r *http.Request, code int32)
	// Echo the User-Agent header
	// (GET /user-agent)
	GetUserAgent(w http.ResponseWriter, r *http.Request)
	// Generate a random UUID
	// (GET /uuid)
	GetUuid(w http.ResponseWriter, r *http.Request)
	// Build and version metadata
	// (GET /version)
	GetVersion(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Delay the response by a given number of seconds
// (GET /delay/{seconds})
func (_ Unimplemented) GetDelay(w http.ResponseWriter, r *http.Request, seconds float64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Echo the incoming request
// (DELETE /echo)
func (_ Unimplemented) DeleteEcho(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Echo the incoming request
// (GET /echo)
func (_ Unimplemented) GetEcho(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Echo the incoming request
// (PATCH /echo)
func (_ Unimplemented) PatchEcho(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Echo the incoming request
// (POST /echo)
func (_ Unimplemented) PostEcho(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Echo the incoming request
// (PUT /echo)
func (_ Unimplemented) PutEcho(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Echo the request headers
// (GET /headers)
func (_ Unimplemented) GetHeaders(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Return the caller's IP address
// (GET /ip)
func (_ Unimplemented) GetIp(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness probe
// (GET /livez)
func (_ Unimplemented) GetLivez(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Readiness probe
// (GET /readyz)
func (_ Unimplemented) GetReadyz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Return the request scheme
// (GET /scheme)
func (_ Unimplemented) GetScheme(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Startup probe
// (GET /startupz)
func (_ Unimplemented) GetStartupz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Return a given HTTP status code
// (GET /status/{code})
func (_ Unimplemented) GetStatus(w http.ResponseWriter, r *http.Request, code int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Echo the User-Agent header
// (GET /user-agent)
func (_ Unimplemented) GetUserAgent(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Generate a random UUID
// (GET /uuid)
func (_ Unimplemented) GetUuid(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Build and version metadata
// (GET /version)
func (_ Unimplemented) GetVersion(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetDelay operation middleware
func (siw *ServerInterfaceWrapper) GetDelay(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "seconds" -------------
	var seconds float64

	err = runtime.BindStyledParameterWithOptions("simple", "seconds", chi.URLParam(r, "seconds"), &seconds, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "number", Format: "double"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "seconds", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDelay(w, r, seconds)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteEcho operation middleware
func (siw *ServerInterfaceWrapper) DeleteEcho(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteEcho(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEcho operation middleware
func (siw *ServerInterfaceWrapper) GetEcho(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEcho(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchEcho operation middleware
func (siw *ServerInterfaceWrapper) PatchEcho(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchEcho(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEcho operation middleware
func (siw *ServerInterfaceWrapper) PostEcho(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEcho(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutEcho operation middleware
func (siw *ServerInterfaceWrapper) PutEcho(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutEcho(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHeaders operation middleware
func (siw *ServerInterfaceWrapper) GetHeaders(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHeaders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetIp operation middleware
func (siw *ServerInterfaceWrapper) GetIp(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLivez operation middleware
func (siw *ServerInterfaceWrapper) GetLivez(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLivez(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetScheme operation middleware
func (siw *ServerInterfaceWrapper) GetScheme(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetScheme(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStartupz operation middleware
func (siw *ServerInterfaceWrapper) GetStartupz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStartupz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetStatus(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "code" -------------
	var code int32

	err = runtime.BindStyledParameterWithOptions("simple", "code", chi.URLParam(r, "code"), &code, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatus(w, r, code)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserAgent operation middleware
func (siw *ServerInterfaceWrapper) GetUserAgent(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserAgent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUuid operation middleware
func (siw *ServerInterfaceWrapper) GetUuid(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUuid(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/delay/{seconds}", wrapper.GetDelay)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/echo", wrapper.DeleteEcho)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/echo", wrapper.GetEcho)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/echo", wrapper.PatchEcho)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/echo", wrapper.PostEcho)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/echo", wrapper.PutEcho)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/headers", wrapper.GetHeaders)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ip", wrapper.GetIp)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/livez", wrapper.GetLivez)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.GetReadyz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/scheme", wrapper.GetScheme)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/startupz", wrapper.GetStartupz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/status/{code}", wrapper.GetStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/user-agent", wrapper.GetUserAgent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/uuid", wrapper.GetUuid)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/version", wrapper.GetVersion)
	})

	return r
}

type EchoBodyTooLargeJSONResponse ErrorResponse

type EchoReflectionJSONResponse EchoResponse

type GetDelayRequestObject struct {
	Seconds float64 `json:"seconds"`
}

type GetDelayResponseObject interface {
	VisitGetDelayResponse(w http.ResponseWriter) error
}

type GetDelay200JSONResponse DelayResponse

func (response GetDelay200JSONResponse) VisitGetDelayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetDelay400JSONResponse ErrorResponse

func (response GetDelay400JSONResponse) VisitGetDelayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteEchoRequestObject struct {
	Body *DeleteEchoTextRequestBody
}

type DeleteEchoResponseObject interface {
	VisitDeleteEchoResponse(w http.ResponseWriter) error
}

type DeleteEcho200JSONResponse struct{ EchoReflectionJSONResponse }

func (response DeleteEcho200JSONResponse) VisitDeleteEchoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteEcho413JSONResponse struct{ EchoBodyTooLargeJSONResponse }

func (response DeleteEcho413JSONResponse) VisitDeleteEchoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type GetEchoRequestObject struct {
}

type GetEchoResponseObject interface {
	VisitGetEchoResponse(w http.ResponseWriter) error
}

type GetEcho200JSONResponse EchoResponse

func (response GetEcho200JSONResponse) VisitGetEchoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PatchEchoRequestObject struct {
	Body *PatchEchoTextRequestBody
}

type PatchEchoResponseObject interface {
	VisitPatchEchoResponse(w http.ResponseWriter) error
}

type PatchEcho200JSONResponse struct{ EchoReflectionJSONResponse }

func (response PatchEcho200JSONResponse) VisitPatchEchoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PatchEcho413JSONResponse struct{ EchoBodyTooLargeJSONResponse }

func (response PatchEcho413JSONResponse) VisitPatchEchoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type PostEchoRequestObject struct {
	Body *PostEchoTextRequestBody
}

type PostEchoResponseObject interface {
	VisitPostEchoResponse(w http.ResponseWriter) error
}

type PostEcho200JSONResponse struct{ EchoReflectionJSONResponse }

func (response PostEcho200JSONResponse) VisitPostEchoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostEcho413JSONResponse struct{ EchoBodyTooLargeJSONResponse }

func (response PostEcho413JSONResponse) VisitPostEchoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type PutEchoRequestObject struct {
	Body *PutEchoTextRequestBody
}

type PutEchoResponseObject interface {
	VisitPutEchoResponse(w http.ResponseWriter) error
}

type PutEcho200JSONResponse struct{ EchoReflectionJSONResponse }

func (response PutEcho200JSONResponse) VisitPutEchoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PutEcho413JSONResponse struct{ EchoBodyTooLargeJSONResponse }

func (response PutEcho413JSONResponse) VisitPutEchoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type GetHeadersRequestObject struct {
}

type GetHeadersResponseObject interface {
	VisitGetHeadersResponse(w http.ResponseWriter) error
}

type GetHeaders200JSONResponse HeadersResponse

func (response GetHeaders200JSONResponse) VisitGetHeadersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetIpRequestObject struct {
}

type GetIpResponseObject interface {
	VisitGetIpResponse(w http.ResponseWriter) error
}

type GetIp200JSONResponse IpResponse

func (response GetIp200JSONResponse) VisitGetIpResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetLivezRequestObject struct {
}

type GetLivezResponseObject interface {
	VisitGetLivezResponse(w http.ResponseWriter) error
}

type GetLivez200JSONResponse LivezResponse

func (response GetLivez200JSONResponse) VisitGetLivezResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyzRequestObject struct {
}

type GetReadyzResponseObject interface {
	VisitGetReadyzResponse(w http.ResponseWriter) error
}

type GetReadyz200JSONResponse ReadyzResponse

func (response GetReadyz200JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyz503JSONResponse ReadyzResponse

func (response GetReadyz503JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetSchemeRequestObject struct {
}

type GetSchemeResponseObject interface {
	VisitGetSchemeResponse(w http.ResponseWriter) error
}

type GetScheme200JSONResponse SchemeResponse

func (response GetScheme200JSONResponse) VisitGetSchemeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetStartupzRequestObject struct {
}

type GetStartupzResponseObject interface {
	VisitGetStartupzResponse(w http.ResponseWriter) error
}

type GetStartupz200JSONResponse StartupzResponse

func (response GetStartupz200JSONResponse) VisitGetStartupzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetStartupz503JSONResponse StartupzResponse

func (response GetStartupz503JSONResponse) VisitGetStartupzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetStatusRequestObject struct {
	Code int32 `json:"code"`
}

type GetStatusResponseObject interface {
	VisitGetStatusResponse(w http.ResponseWriter) error
}

type GetStatus400JSONResponse ErrorResponse

func (response GetStatus400JSONResponse) VisitGetStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetStatusdefaultJSONResponse struct {
	Body       StatusResponse
	StatusCode int
}

func (response GetStatusdefaultJSONResponse) VisitGetStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetUserAgentRequestObject struct {
}

type GetUserAgentResponseObject interface {
	VisitGetUserAgentResponse(w http.ResponseWriter) error
}

type GetUserAgent200JSONResponse UserAgentResponse

func (response GetUserAgent200JSONResponse) VisitGetUserAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetUuidRequestObject struct {
}

type GetUuidResponseObject interface {
	VisitGetUuidResponse(w http.ResponseWriter) error
}

type GetUuid200JSONResponse UuidResponse

func (response GetUuid200JSONResponse) VisitGetUuidResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetVersionRequestObject struct {
}

type GetVersionResponseObject interface {
	VisitGetVersionResponse(w http.ResponseWriter) error
}

type GetVersion200JSONResponse VersionResponse

func (response GetVersion200JSONResponse) VisitGetVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Delay the response by a given number of seconds
	// (GET /delay/{seconds})
	GetDelay(ctx context.Context, request GetDelayRequestObject) (GetDelayResponseObject, error)
	// Echo the incoming request
	// (DELETE /echo)
	DeleteEcho(ctx context.Context, request DeleteEchoRequestObject) (DeleteEchoResponseObject, error)
	// Echo the incoming request
	// (GET /echo)
	GetEcho(ctx context.Context, request GetEchoRequestObject) (GetEchoResponseObject, error)
	// Echo the incoming request
	// (PATCH /echo)
	PatchEcho(ctx context.Context, request PatchEchoRequestObject) (PatchEchoResponseObject, error)
	// Echo the incoming request
	// (POST /echo)
	PostEcho(ctx context.Context, request PostEchoRequestObject) (PostEchoResponseObject, error)
	// Echo the incoming request
	// (PUT /echo)
	PutEcho(ctx context.Context, request PutEchoRequestObject) (PutEchoResponseObject, error)
	// Echo the request headers
	// (GET /headers)
	GetHeaders(ctx context.Context, request GetHeadersRequestObject) (GetHeadersResponseObject, error)
	// Return the caller's IP address
	// (GET /ip)
	GetIp(ctx context.Context, request GetIpRequestObject) (GetIpResponseObject, error)
	// Liveness probe
	// (GET /livez)
	GetLivez(ctx context.Context, request GetLivezRequestObject) (GetLivezResponseObject, error)
	// Readiness probe
	// (GET /readyz)
	GetReadyz(ctx context.Context, request GetReadyzRequestObject) (GetReadyzResponseObject, error)
	// Return the request scheme
	// (GET /scheme)
	GetScheme(ctx context.Context, request GetSchemeRequestObject) (GetSchemeResponseObject, error)
	// Startup probe
	// (GET /startupz)
	GetStartupz(ctx context.Context, request GetStartupzRequestObject) (GetStartupzResponseObject, error)
	// Return a given HTTP status code
	// (GET /status/{code})
	GetStatus(ctx context.Context, request GetStatusRequestObject) (GetStatusResponseObject, error)
	// Echo the User-Agent header
	// (GET /user-agent)
	GetUserAgent(ctx context.Context, request GetUserAgentRequestObject) (GetUserAgentResponseObject, error)
	// Generate a random UUID
	// (GET /uuid)
	GetUuid(ctx context.Context, request GetUuidRequestObject) (GetUuidResponseObject, error)
	// Build and version metadata
	// (GET /version)
	GetVersion(ctx context.Context, request GetVersionRequestObject) (GetVersionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetDelay operation middleware
func (sh *strictHandler) GetDelay(w http.ResponseWriter, r *http.Request, seconds float64) {
	var request GetDelayRequestObject

	request.Seconds = seconds

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDelay(ctx, request.(GetDelayRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDelay")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDelayResponseObject); ok {
		if err := validResponse.VisitGetDelayResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteEcho operation middleware
func (sh *strictHandler) DeleteEcho(w http.ResponseWriter, r *http.Request) {
	var request DeleteEchoRequestObject

	data, err := io.ReadAll(r.Body)
	if err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't read body: %w", err))
		return
	}
	if len(data) > 0 {
		body := DeleteEchoTextRequestBody(data)
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteEcho(ctx, request.(DeleteEchoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteEcho")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteEchoResponseObject); ok {
		if err := validResponse.VisitDeleteEchoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetEcho operation middleware
func (sh *strictHandler) GetEcho(w http.ResponseWriter, r *http.Request) {
	var request GetEchoRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEcho(ctx, request.(GetEchoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEcho")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEchoResponseObject); ok {
		if err := validResponse.VisitGetEchoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchEcho operation middleware
func (sh *strictHandler) PatchEcho(w http.ResponseWriter, r *http.Request) {
	var request PatchEchoRequestObject

	data, err := io.ReadAll(r.Body)
	if err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't read body: %w", err))
		return
	}
	if len(data) > 0 {
		body := PatchEchoTextRequestBody(data)
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchEcho(ctx, request.(PatchEchoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchEcho")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchEchoResponseObject); ok {
		if err := validResponse.VisitPatchEchoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostEcho operation middleware
func (sh *strictHandler) PostEcho(w http.ResponseWriter, r *http.Request) {
	var request PostEchoRequestObject

	data, err := io.ReadAll(r.Body)
	if err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't read body: %w", err))
		return
	}
	if len(data) > 0 {
		body := PostEchoTextRequestBody(data)
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostEcho(ctx, request.(PostEchoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostEcho")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostEchoResponseObject); ok {
		if err := validResponse.VisitPostEchoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutEcho operation middleware
func (sh *strictHandler) PutEcho(w http.ResponseWriter, r *http.Request) {
	var request PutEchoRequestObject

	data, err := io.ReadAll(r.Body)
	if err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't read body: %w", err))
		return
	}
	if len(data) > 0 {
		body := PutEchoTextRequestBody(data)
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutEcho(ctx, request.(PutEchoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutEcho")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutEchoResponseObject); ok {
		if err := validResponse.VisitPutEchoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHeaders operation middleware
func (sh *strictHandler) GetHeaders(w http.ResponseWriter, r *http.Request) {
	var request GetHeadersRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHeaders(ctx, request.(GetHeadersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHeaders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHeadersResponseObject); ok {
		if err := validResponse.VisitGetHeadersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetIp operation middleware
func (sh *strictHandler) GetIp(w http.ResponseWriter, r *http.Request) {
	var request GetIpRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetIp(ctx, request.(GetIpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetIp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetIpResponseObject); ok {
		if err := validResponse.VisitGetIpResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLivez operation middleware
func (sh *strictHandler) GetLivez(w http.ResponseWriter, r *http.Request) {
	var request GetLivezRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLivez(ctx, request.(GetLivezRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLivez")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLivezResponseObject); ok {
		if err := validResponse.VisitGetLivezResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadyz operation middleware
func (sh *strictHandler) GetReadyz(w http.ResponseWriter, r *http.Request) {
	var request GetReadyzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadyz(ctx, request.(GetReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadyz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadyzResponseObject); ok {
		if err := validResponse.VisitGetReadyzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetScheme operation middleware
func (sh *strictHandler) GetScheme(w http.ResponseWriter, r *http.Request) {
	var request GetSchemeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetScheme(ctx, request.(GetSchemeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetScheme")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSchemeResponseObject); ok {
		if err := validResponse.VisitGetSchemeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetStartupz operation middleware
func (sh *strictHandler) GetStartupz(w http.ResponseWriter, r *http.Request) {
	var request GetStartupzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetStartupz(ctx, request.(GetStartupzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStartupz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetStartupzResponseObject); ok {
		if err := validResponse.VisitGetStartupzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetStatus operation middleware
func (sh *strictHandler) GetStatus(w http.ResponseWriter, r *http.Request, code int32) {
	var request GetStatusRequestObject

	request.Code = code

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetStatus(ctx, request.(GetStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetStatusResponseObject); ok {
		if err := validResponse.VisitGetStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUserAgent operation middleware
func (sh *strictHandler) GetUserAgent(w http.ResponseWriter, r *http.Request) {
	var request GetUserAgentRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserAgent(ctx, request.(GetUserAgentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserAgent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUserAgentResponseObject); ok {
		if err := validResponse.VisitGetUserAgentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUuid operation middleware
func (sh *strictHandler) GetUuid(w http.ResponseWriter, r *http.Request) {
	var request GetUuidRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUuid(ctx, request.(GetUuidRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUuid")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUuidResponseObject); ok {
		if err := validResponse.VisitGetUuidResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVersion operation middleware
func (sh *strictHandler) GetVersion(w http.ResponseWriter, r *http.Request) {
	var request GetVersionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVersion(ctx, request.(GetVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVersion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVersionResponseObject); ok {
		if err := validResponse.VisitGetVersionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5Fp7b9y2sv8qA90L3BTQvhynt3H/cm5yW6Np65O47cHpMQJKnF2xkUiVpNbZGv7uB0NSu3pwvbaPfdqi",
	"QICsJYqa+c2L8xtdJ7mqaiVRWpOcXCcaf23Q2FeKC3QX3uSFeqX4hn7nSlqUln5a/GRndcmEpL9MXmDF",
	"6Bd+YlVdYnKSFFiWKkkTu6npT2O1kKvk5uYmTTiaXIvaCiWTk+RUgnK/WQnh9ZApvgGrQOOyxNxCxvKP",
	"U7go0N8RBjQyDsyAkwFIHGCSA+aFQg5r1BmzokqhqWmfz4/hG/Fq+k+Z0Ps1mlpJ01fwQqm3TK9woCir",
	"61LkjOSb/WLUQN3/1rhMTpL/mu1QnPm7ZvZGa6XfhVfFFCd1egrjpxyRG7AFQsU+iaqpwIjfEGzBLORM",
	"QoZBw2lykzrR33mEhJfscQR32+6X+7Q1i1AS1NKJK2SuKiFXrUJTB3TYkV74Gku22e5K8nEuvNXPtapR",
	"W+dwS1YaTJO6c+k64fSs/zHETzZVhpqkMJgrGcBrDQxXzIB7mhBLd965SJOl0hWzyUnCVZOVuPNUv2Vw",
	"lF8boZEnJz8HIS63y1T2C+aWzPAaa5QcZb75vwLzj/dUrkJjmHe7XfDw7Zbk6wWy0habcTClibHMNm4f",
	"lE1FcqqPpCj5XpIm5qOoa+Qk9m5zt2IYln1lw7YxbXvecT9Vs5BHDoWBj2GK+W0gT+G7pixhqTRUaAvl",
	"DO2CQusNSOWffGaavKCs8NWbi88o2tNIQpJNWTKy+InVDUYwLZBx1OZQmHztln3LanrGC9U34ldvLmIm",
	"U1qsfNoc45CzskT9Pwb8Ijg7B8a5RmN67psczZ9P59PF4vn0+Cj2jprZoi/MjNVitl7MCNzYE782qDf3",
	"UtldxLge/h48K6ytQWmg/81n+5NFunVfWpmk7j/Td1t/6ZDnBkMECFq9dkbd4r9VIOrkvdx9Py/3sTeC",
	"5RSKpmJyQoWL3A86t1tg3KN9S/tIhFxxhKqhECH8fJZjcoWwmM8nL16+PAiMFyum7M6qexW9ToTFyv0Y",
	"eU64wLRmmyRSLCpW12RstQTJKjRUj22BQkMpjKXLa1Y2aFJoDHIX4pmyBXx9cXEOwWyutjtTQs00q9DS",
	"xWfI8gIqtgFW18g0VEq7YilByRyHGeA6Oc1zrC2hMaqOl2nyg0E9OV25+vlzkje6nH0x/d/pIrm82Yua",
	"eaCT3D/HDMzZbhAz6Fn9QKmePjUNtAgvjCnxVqzxtwfqEa2Kj1gD3yHjm4cKl9MhwdwWa7d5xPCwcdNz",
	"8EqstHPqHgykLRUFZexKY+yWRi7G12NuP4aWEhplWKnsB/+7h3R7+05gpy06MdTfu3z9UJf4Q1arW0rQ",
	"e8u0beo/opflSi7FKuJGt7jf3XzJkNJI5dv9IsguB9Uw3H8Ed3JrHgqv4nucyZWtbtXWaBstBw3I0Xze",
	"aUGEtM87yVJIiytqQQbFNJ6WpZIid70zM0pCXWhm0JVR8t6OJCmIJXyU6kr2M/b33xzE06kbA5FqpiuZ",
	"D8SxoZrLVqFn3cnUqb6HZOtsEZWwEfyhwjWCxw5ymkmuqnIDK5SomfWEg6GD3DH88MPZ6z6+i+wl/zzL",
	"+STLlnxynB3xycvsBZ+w7Au+zDJ+nDmP3nqDe+1BrWlRTN8fvSQPbdEaUfIPVlSDhvRofvT5ZE7/Lhbz",
	"kzn9+0dXZs4sTtxjkd5iJewHUwz4IZbli6Pn0eXqQ4Cz/8RKLaZHx9PjaB+Mei3yURe9VrXJhJywWsSe",
	"ir5mPl1M54czTHjhbpOdnmkXxp4+Y4PRvkIu1djPvhVSVKyE72uUp+dn4HOfBlNj7sL7Na6/r80rIUE3",
	"kt4FKHmthLTuSGaFdfrslp2en3XkbTWllrRGSRCdJHR2ex66J+cQM8d7zK4DvXJD11Zox+L+xIQ127QT",
	"aiXyCEOT4ZLO6Z6k4UKuPLPnXgTCQE6neQ7MwmLePvQllEyvUIdeAZhGyEtW0ULfT9BjU/gOV8yKNbbr",
	"NgJLDgyO5/MtK+Rfd8WEdZcwt2ZLQORM5liWroi5psPlUNRrd/RtVxHYqrG+v6DwcevPODX9aB3V5TBs",
	"O5Xk5Oc7klcqwPBsPlnMPyMz0nm8bWapfyKX9KuTrkd6LiNCxEaprsAuJieLOVVt6f+YjzmwywFbejSf",
	"PxrP2KcE9xKkgcpjS3L+vm85rBwVevyIct2HuG2FIL+VwfcC99lUFdMbF4C0oMdLZhtgsBJrlGMnoNBl",
	"K/KZ5C2zdAZLLmlDT914OhRt5PTxzh00DHC0TJRm3/n1xB9RPFGSArlWOuqt07bzTsf9XhoOzKkLkC51",
	"FwuI107aN5522o0X9nJNvQnEbDt+uIk7YnyHsG42IMjJTxbP7/ZYbyTQtyfdjiLbsdyZdInFUQfRdPmf",
	"MxYZyRtsT77a2uaJ4vwR5wkPtkHNbF78WULmnIT9K0dMrYz90xhLGfuXtlXz5zFV8xe2FJ0gOqzzrUXJ",
	"tjxGS79rzFGskcOVsEX3EDaNFZSvt7OWJ6spQ/b9wHg96LG3igzW7QVQ1HfCbuSnt3GJI/jO6qdErjMc",
	"2APabUx/Hz+vc+i+wkO71XtRLMUaf9sL5LlWORozUbLcAC2VBKAj8qbwWoFU1v8F557Qfv+3t6A0vEPu",
	"ZuUao6i6ecJTAtsfWESwDYpRq8DKSJ/wttW11irDDnrvfHsf0HOE+n74HGFr4KpAW4SGqaNT++lM+LrG",
	"RTVYzZZLkUdh86OOp8RtMEyJHRAj8ruu78X8+e8nBvlhK8ogKhgXdzDkbiRxMKHcc0IBPxUoe4mNaS3W",
	"SJtp1awKYGB149rXWqtPm7T7FmHAso8oYalV5W78ffL/Sl8xzZFPzrWyKiTKL0GRk10Jg+DYFFfius4n",
	"TGBPwKKuhHRk6cXb91uiKFdS+rK4pzvxU5+ndMDBXOlAKQmt1P5M2F+4NwmaMN+5ayB3gzg8CwUzQApR",
	"h82j4dtOkZ4Uv+Gk6kDstNKLnfCPHs3/hkzGirIEISkyVrGqF/Y+FN1u8DK7zhXHm1uC3JGgZnewGs2P",
	"aq3WgiNvP/ugU7KnMHsfhTBYs1Lw8fOxr0W+BCY3Png9U+qJUjNkSveEZDtdO8hwjoRxVceFyrMgyj6S",
	"042c7sRwxmdpW4rzxcuXHY5zMZ+P52wjmvN3pBN7pjOgGmsEAVdgMLAz5NQPB5esKe1jBk13IrpH1MiA",
	"s5U923TOgntSZMt7DrfpBFLwLx9H/QnhwUq5+4gn1Kh79i7bgeZTZszx1PRA0dlptbeFGSm+t/K0Y81b",
	"sWR3m3KO8fPDy6eDrjvOjZOJTm4n4fp4CNdXQZetfm7dXqg6A8KA1kjhH7fjvyfTeTjSjagdlkCFlnFm",
	"2VDvV40ouSNJ1oOV8QIWRqrxzH56fgbrBWTM+GqUpEmjy91Hpgnl07DpyL/8O9LwUbMvop6+cUPTrVz9",
	"YWYoCq2EN+nYb12kTDpU8nYD/6kwUqS4j4oPsFKd97XeMH7fm/7muk1uPvdN6DGxFDiux53dQ547uLmQ",
	"Vive5AhMAtNWLEUuWJlCphpJJ4PtXCkMxLZvaAdIN5c3/woAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
