// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (user_id, name, balance_cents)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, balance_cents, created_at, updated_at
`

type CreateAccountParams struct {
	UserID       pgtype.UUID
	Name         string
	BalanceCents int64
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.UserID, arg.Name, arg.BalanceCents)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.BalanceCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, user_id, name, balance_cents, created_at, updated_at
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.BalanceCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccountsByUser = `-- name: ListAccountsByUser :many
SELECT id, user_id, name, balance_cents, created_at, updated_at
FROM accounts
WHERE user_id = $1
ORDER BY id
`

func (q *Queries) ListAccountsByUser(ctx context.Context, userID pgtype.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.BalanceCents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAccounts = `-- name: ListAllAccounts :many
SELECT a.id, u.username AS owner_username, a.name, a.balance_cents, a.created_at
FROM accounts a
JOIN users u ON u.id = a.user_id
ORDER BY u.username, a.id
`

type ListAllAccountsRow struct {
	ID            pgtype.UUID
	OwnerUsername string
	Name          string
	BalanceCents  int64
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) ListAllAccounts(ctx context.Context) ([]ListAllAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAllAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllAccountsRow{}
	for rows.Next() {
		var i ListAllAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUsername,
			&i.Name,
			&i.BalanceCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
