// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listTransfers = `-- name: ListTransfers :many
SELECT
    t.id,
    t.from_account_id,
    fa.name AS from_account_name,
    t.to_account_id,
    ta.name AS to_account_name,
    t.amount_cents,
    t.created_at
FROM transfers t
JOIN accounts fa ON fa.id = t.from_account_id
JOIN accounts ta ON ta.id = t.to_account_id
ORDER BY t.created_at DESC, t.id
`

type ListTransfersRow struct {
	ID              pgtype.UUID
	FromAccountID   pgtype.UUID
	FromAccountName string
	ToAccountID     pgtype.UUID
	ToAccountName   string
	AmountCents     int64
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) ListTransfers(ctx context.Context) ([]ListTransfersRow, error) {
	rows, err := q.db.Query(ctx, listTransfers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransfersRow{}
	for rows.Next() {
		var i ListTransfersRow
		if err := rows.Scan(
			&i.ID,
			&i.FromAccountID,
			&i.FromAccountName,
			&i.ToAccountID,
			&i.ToAccountName,
			&i.AmountCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
